import { Landmark, TrendingUp, Trophy, Mountain, Waves, Building2, Users2, Clapperboard, type LucideIcon } from 'lucide-react';

// The 핫이슈 tab's "하이브리드 테마 랭킹 위젯" (owner instruction 2026-09-04, deepened
// 2026-09-04): a row of theme chips sitting directly above HotIssueNewsList's
// live feed. Tapping a chip expands its top-10 countdown; "11~50위 보기" /
// "51~100위 보기" progressively widen the visible window
// (LOAD_MORE_TIERS). Every ranked row here is a factual, independently
// verifiable snapshot (heritage-site counts, elevations, river lengths,
// nominal GDP, box-office gross, population, building height, historical
// milestones) -- deliberately NOT padded with invented filler once real,
// confidently-sourceable data runs out, so `entries.length` legitimately
// varies per theme (30-100) and the widget shows a "collectingMore" state
// past it rather than fabricate ranks nobody can verify. Depth per theme
// reflects genuine confidence, not a mechanical round number: country-level
// statistics (population, GDP, heritage-site counts) extend furthest since
// misordering two similarly-sized economies is a minor precision issue, while
// uniquely-named structures (buildings, mountains, rivers) stay shallower
// because a wrong/duplicated proper noun is a much more visible error.
// Entry labels stay in English across every locale by design (proper nouns /
// figures a Korean, Thai, or Estonian visitor reads identically) -- only the
// theme title/description and the widget's chrome strings are localized
// (messages/*.json -> `GlobalRankings` namespace).

export type GlobalRankingThemeKey =
  | 'heritage'
  | 'gdp'
  | 'records'
  | 'mountains'
  | 'rivers'
  | 'buildings'
  | 'population'
  | 'filmBoxOffice';

export interface GlobalRankingEntry {
  /** Rank position, 1-indexed. */
  rank: number;
  /** The ranked subject -- a country, structure, film, or milestone. Kept
   *  untranslated (see file banner). */
  name: string;
  /** Short factual qualifier shown beside the name (figure, year, location). */
  note: string;
}

export interface GlobalRankingTheme {
  key: GlobalRankingThemeKey;
  icon: LucideIcon;
  color: string;
  entries: GlobalRankingEntry[];
}

/** Progressive reveal windows the "11~50위 보기" / "51~100위 보기" buttons step
 *  through -- capped per-theme at `entries.length` (see GlobalThemeRankings). */
export const LOAD_MORE_TIERS = [10, 50, 100] as const;

export const GLOBAL_RANKING_THEMES: GlobalRankingTheme[] = [
  {
    key: 'heritage',
    icon: Landmark,
    color: '#facc15',
    entries: [
      { rank: 1, name: 'Italy', note: '60 sites' },
      { rank: 2, name: 'China', note: '59 sites' },
      { rank: 3, name: 'Germany', note: '54 sites' },
      { rank: 4, name: 'France', note: '53 sites' },
      { rank: 5, name: 'Spain', note: '50 sites' },
      { rank: 6, name: 'India', note: '43 sites' },
      { rank: 7, name: 'Mexico', note: '35 sites' },
      { rank: 8, name: 'United Kingdom', note: '34 sites' },
      { rank: 9, name: 'Russia', note: '32 sites' },
      { rank: 10, name: 'Iran', note: '28 sites' },
      { rank: 11, name: 'Japan', note: '26 sites' },
      { rank: 12, name: 'United States', note: '26 sites' },
      { rank: 13, name: 'Brazil', note: '23 sites' },
      { rank: 14, name: 'Australia', note: '20 sites' },
      { rank: 15, name: 'Canada', note: '20 sites' },
      { rank: 16, name: 'Türkiye', note: '21 sites' },
      { rank: 17, name: 'Greece', note: '19 sites' },
      { rank: 18, name: 'Portugal', note: '17 sites' },
      { rank: 19, name: 'Poland', note: '17 sites' },
      { rank: 20, name: 'South Korea', note: '16 sites' },
      { rank: 21, name: 'Czechia', note: '16 sites' },
      { rank: 22, name: 'Belgium', note: '15 sites' },
      { rank: 23, name: 'Sweden', note: '15 sites' },
      { rank: 24, name: 'Switzerland', note: '13 sites' },
      { rank: 25, name: 'Netherlands', note: '13 sites' },
      { rank: 26, name: 'Peru', note: '13 sites' },
      { rank: 27, name: 'Austria', note: '12 sites' },
      { rank: 28, name: 'Argentina', note: '12 sites' },
      { rank: 29, name: 'Croatia', note: '11 sites' },
      { rank: 30, name: 'Denmark', note: '11 sites' },
      { rank: 31, name: 'Indonesia', note: '10 sites' },
      { rank: 32, name: 'Bulgaria', note: '10 sites' },
      { rank: 33, name: 'South Africa', note: '10 sites' },
      { rank: 34, name: 'Israel', note: '9 sites' },
      { rank: 35, name: 'Hungary', note: '9 sites' },
      { rank: 36, name: 'Ethiopia', note: '9 sites' },
      { rank: 37, name: 'Morocco', note: '9 sites' },
      { rank: 38, name: 'Colombia', note: '9 sites' },
      { rank: 39, name: 'Cuba', note: '9 sites' },
      { rank: 40, name: 'Romania', note: '9 sites' },
      { rank: 41, name: 'Uzbekistan', note: '9 sites' },
      { rank: 42, name: 'Egypt', note: '7 sites' },
      { rank: 43, name: 'Tunisia', note: '8 sites' },
      { rank: 44, name: 'Vietnam', note: '8 sites' },
      { rank: 45, name: 'Chile', note: '7 sites' },
      { rank: 46, name: 'Thailand', note: '7 sites' },
      { rank: 47, name: 'Sri Lanka', note: '8 sites' },
      { rank: 48, name: 'Finland', note: '7 sites' },
      { rank: 49, name: 'Slovakia', note: '8 sites' },
      { rank: 50, name: 'Ukraine', note: '8 sites' },
      { rank: 51, name: 'Norway', note: '8 sites' },
      { rank: 52, name: 'Philippines', note: '6 sites' },
      { rank: 53, name: 'Kazakhstan', note: '6 sites' },
      { rank: 54, name: 'Mongolia', note: '6 sites' },
      { rank: 55, name: 'Pakistan', note: '6 sites' },
      { rank: 56, name: 'Slovenia', note: '5 sites' },
      { rank: 57, name: 'Serbia', note: '5 sites' },
      { rank: 58, name: 'Lithuania', note: '5 sites' },
      { rank: 59, name: 'Bolivia', note: '7 sites' },
      { rank: 60, name: 'Ecuador', note: '5 sites' },
      { rank: 61, name: 'Senegal', note: '7 sites' },
      { rank: 62, name: 'Ivory Coast', note: '5 sites' },
      { rank: 63, name: 'Zimbabwe', note: '5 sites' },
      { rank: 64, name: 'Tanzania', note: '7 sites' },
      { rank: 65, name: 'DR Congo', note: '5 sites' },
      { rank: 66, name: 'Georgia', note: '4 sites' },
      { rank: 67, name: 'Belarus', note: '4 sites' },
      { rank: 68, name: 'Nepal', note: '4 sites' },
      { rank: 69, name: 'Malaysia', note: '4 sites' },
      { rank: 70, name: 'Panama', note: '5 sites' },
    ],
  },
  {
    key: 'gdp',
    icon: TrendingUp,
    color: '#60a5fa',
    entries: [
      { rank: 1, name: 'United States', note: '~$27T nominal GDP' },
      { rank: 2, name: 'China', note: '~$18T' },
      { rank: 3, name: 'Germany', note: '~$4.5T' },
      { rank: 4, name: 'Japan', note: '~$4.1T' },
      { rank: 5, name: 'India', note: '~$3.9T' },
      { rank: 6, name: 'United Kingdom', note: '~$3.3T' },
      { rank: 7, name: 'France', note: '~$3.0T' },
      { rank: 8, name: 'Brazil', note: '~$2.3T' },
      { rank: 9, name: 'Italy', note: '~$2.3T' },
      { rank: 10, name: 'Canada', note: '~$2.1T' },
      { rank: 11, name: 'Russia', note: '~$2.0T' },
      { rank: 12, name: 'South Korea', note: '~$1.8T' },
      { rank: 13, name: 'Australia', note: '~$1.7T' },
      { rank: 14, name: 'Spain', note: '~$1.6T' },
      { rank: 15, name: 'Mexico', note: '~$1.5T' },
      { rank: 16, name: 'Indonesia', note: '~$1.4T' },
      { rank: 17, name: 'Netherlands', note: '~$1.1T' },
      { rank: 18, name: 'Saudi Arabia', note: '~$1.1T' },
      { rank: 19, name: 'Türkiye', note: '~$1.1T' },
      { rank: 20, name: 'Switzerland', note: '~$0.9T' },
      { rank: 21, name: 'Poland', note: '~$0.85T' },
      { rank: 22, name: 'Taiwan', note: '~$0.8T' },
      { rank: 23, name: 'Belgium', note: '~$0.65T' },
      { rank: 24, name: 'Argentina', note: '~$0.64T' },
      { rank: 25, name: 'Sweden', note: '~$0.59T' },
      { rank: 26, name: 'Ireland', note: '~$0.56T' },
      { rank: 27, name: 'Israel', note: '~$0.54T' },
      { rank: 28, name: 'United Arab Emirates', note: '~$0.53T' },
      { rank: 29, name: 'Thailand', note: '~$0.53T' },
      { rank: 30, name: 'Singapore', note: '~$0.5T' },
      { rank: 31, name: 'Nigeria', note: '~$0.48T' },
      { rank: 32, name: 'Norway', note: '~$0.48T' },
      { rank: 33, name: 'Austria', note: '~$0.47T' },
      { rank: 34, name: 'Egypt', note: '~$0.45T' },
      { rank: 35, name: 'Philippines', note: '~$0.44T' },
      { rank: 36, name: 'Bangladesh', note: '~$0.44T' },
      { rank: 37, name: 'Vietnam', note: '~$0.43T' },
      { rank: 38, name: 'Malaysia', note: '~$0.43T' },
      { rank: 39, name: 'Denmark', note: '~$0.41T' },
      { rank: 40, name: 'Colombia', note: '~$0.38T' },
      { rank: 41, name: 'Romania', note: '~$0.35T' },
      { rank: 42, name: 'Chile', note: '~$0.35T' },
      { rank: 43, name: 'Czechia', note: '~$0.34T' },
      { rank: 44, name: 'Pakistan', note: '~$0.34T' },
      { rank: 45, name: 'Iraq', note: '~$0.3T' },
      { rank: 46, name: 'Portugal', note: '~$0.28T' },
      { rank: 47, name: 'Peru', note: '~$0.27T' },
      { rank: 48, name: 'New Zealand', note: '~$0.26T' },
      { rank: 49, name: 'Kazakhstan', note: '~$0.26T' },
      { rank: 50, name: 'Qatar', note: '~$0.22T' },
      { rank: 51, name: 'Hungary', note: '~$0.21T' },
      { rank: 52, name: 'Ukraine', note: '~$0.18T' },
      { rank: 53, name: 'Kuwait', note: '~$0.16T' },
      { rank: 54, name: 'Ethiopia', note: '~$0.16T' },
      { rank: 55, name: 'Morocco', note: '~$0.15T' },
      { rank: 56, name: 'Dominican Republic', note: '~$0.13T' },
      { rank: 57, name: 'Guatemala', note: '~$0.11T' },
      { rank: 58, name: 'Oman', note: '~$0.11T' },
      { rank: 59, name: 'Bulgaria', note: '~$0.1T' },
      { rank: 60, name: 'Kenya', note: '~$0.12T' },
      { rank: 61, name: 'Slovakia', note: '~$0.13T' },
      { rank: 62, name: 'Ecuador', note: '~$0.12T' },
      { rank: 63, name: 'Angola', note: '~$0.1T' },
      { rank: 64, name: 'Uzbekistan', note: '~$0.09T' },
      { rank: 65, name: 'DR Congo', note: '~$0.07T' },
      { rank: 66, name: 'Sri Lanka', note: '~$0.085T' },
      { rank: 67, name: 'Myanmar', note: '~$0.065T' },
      { rank: 68, name: 'Luxembourg', note: '~$0.085T' },
      { rank: 69, name: 'Panama', note: '~$0.08T' },
      { rank: 70, name: 'Costa Rica', note: '~$0.075T' },
    ],
  },
  {
    key: 'records',
    icon: Trophy,
    color: '#e879f9',
    entries: [
      { rank: 1, name: 'Cuneiform script invented', note: 'Sumer, c. 3400 BCE' },
      { rank: 2, name: 'Egyptian hieroglyphic writing emerges', note: 'Egypt, c. 3200 BCE' },
      { rank: 3, name: 'The wheel adopted for transport', note: 'Mesopotamia, c. 3500 BCE' },
      { rank: 4, name: 'Great Pyramid of Giza completed', note: 'Egypt, c. 2560 BCE' },
      { rank: 5, name: 'Bronze Age metallurgy spreads', note: 'Near East, c. 3300 BCE' },
      { rank: 6, name: 'Indus Valley Civilization cities flourish', note: 'South Asia, c. 2500 BCE' },
      { rank: 7, name: 'Code of Hammurabi inscribed', note: 'Babylon, c. 1754 BCE' },
      { rank: 8, name: 'Iron Age begins', note: 'Anatolia, c. 1200 BCE' },
      { rank: 9, name: 'Phoenician alphabet spreads', note: 'Mediterranean, c. 1050 BCE' },
      { rank: 10, name: 'Great Wall of China begun', note: 'China, 7th century BCE' },
      { rank: 11, name: 'First Olympic Games held', note: 'Greece, 776 BCE' },
      { rank: 12, name: 'Buddhism founded', note: 'India, c. 5th century BCE' },
      { rank: 13, name: 'Library of Alexandria founded', note: 'Egypt, c. 285 BCE' },
      { rank: 14, name: "Confucius's teachings recorded", note: 'China, 5th century BCE' },
      { rank: 15, name: 'Roman Republic established', note: 'Rome, 509 BCE' },
      { rank: 16, name: 'Qin Shi Huang unifies China', note: 'China, 221 BCE' },
      { rank: 17, name: "Julius Caesar's Rome", note: 'Rome, 1st century BCE' },
      { rank: 18, name: 'Paper invented', note: 'China, c. 105 CE' },
      { rank: 19, name: 'Roman Empire reaches its height', note: 'Rome, 2nd century CE' },
      { rank: 20, name: 'Silk Road trade networks flourish', note: 'Eurasia, 1st-2nd century CE' },
      { rank: 21, name: 'Constantine legalizes Christianity', note: 'Rome, 313 CE' },
      { rank: 22, name: 'Fall of the Western Roman Empire', note: 'Europe, 476 CE' },
      { rank: 23, name: 'Islam founded', note: 'Arabia, 7th century CE' },
      { rank: 24, name: 'Tang Dynasty golden age', note: 'China, 7th-9th century CE' },
      { rank: 25, name: 'Charlemagne crowned Holy Roman Emperor', note: 'Europe, 800 CE' },
      { rank: 26, name: 'Great Library of Baghdad (House of Wisdom) flourishes', note: 'Abbasid Caliphate, 9th century' },
      { rank: 27, name: 'Printing with movable type (Bi Sheng)', note: 'China, c. 1040' },
      { rank: 28, name: 'Great Schism splits Christianity', note: 'Europe, 1054' },
      { rank: 29, name: 'Compass adopted for navigation', note: 'China, 11th century' },
      { rank: 30, name: 'University of Bologna founded, first modern university', note: 'Italy, 1088' },
      { rank: 31, name: 'Angkor Wat constructed', note: 'Khmer Empire, 12th century' },
      { rank: 32, name: 'Magna Carta signed', note: 'England, 1215' },
      { rank: 33, name: 'Mongol Empire at its peak', note: 'Eurasia, 13th century' },
      { rank: 34, name: "Marco Polo's travels to China", note: 'Asia, 1271-1295' },
      { rank: 35, name: 'Black Death pandemic', note: 'Eurasia, 1347-1351' },
      { rank: 36, name: "Gutenberg's printing press", note: 'Germany, c. 1440' },
      { rank: 37, name: 'Fall of Constantinople', note: 'Byzantium, 1453' },
      { rank: 38, name: 'Columbus reaches the Americas', note: 'Atlantic, 1492' },
      { rank: 39, name: 'Vasco da Gama reaches India by sea', note: 'Indian Ocean, 1498' },
      { rank: 40, name: "Leonardo da Vinci's Renaissance works", note: 'Italy, late 15th century' },
      { rank: 41, name: 'Copernicus proposes heliocentrism', note: 'Poland, 1543' },
      { rank: 42, name: "Magellan's expedition circumnavigates the globe", note: 'Global, 1522' },
      { rank: 43, name: "Shakespeare's plays performed", note: 'England, late 16th century' },
      { rank: 44, name: "Galileo's telescope observations", note: 'Italy, 1609' },
      { rank: 45, name: "Newton's Principia Mathematica", note: 'England, 1687' },
      { rank: 46, name: 'Vaccination pioneered by Edward Jenner', note: 'England, 1796' },
      { rank: 47, name: 'Industrial Revolution begins', note: 'England, 1760s' },
      { rank: 48, name: 'American Declaration of Independence', note: 'USA, 1776' },
      { rank: 49, name: 'French Revolution begins', note: 'France, 1789' },
      { rank: 50, name: 'First steam locomotive runs', note: 'England, 1804' },
      { rank: 51, name: "Napoleon's Napoleonic Code enacted", note: 'France, 1804' },
      { rank: 52, name: 'Steam-powered factories transform textiles', note: 'England, 1780s' },
      { rank: 53, name: 'Darwin publishes On the Origin of Species', note: 'England, 1859' },
      { rank: 54, name: 'Transatlantic telegraph cable completed', note: 'Atlantic, 1866' },
      { rank: 55, name: 'Suez Canal opens', note: 'Egypt, 1869' },
      { rank: 56, name: 'Alexander Graham Bell patents the telephone', note: 'USA, 1876' },
      { rank: 57, name: "Edison's practical incandescent light bulb", note: 'USA, 1879' },
      { rank: 58, name: 'Eiffel Tower completed', note: 'France, 1889' },
      { rank: 59, name: 'First modern Olympic Games', note: 'Greece, 1896' },
      { rank: 60, name: 'Suffrage movements win women the vote', note: 'Global, 1893-1920' },
      { rank: 61, name: "Wright brothers' first powered flight", note: 'USA, 1903' },
      { rank: 62, name: 'Einstein publishes special relativity', note: 'Germany, 1905' },
      { rank: 63, name: "Ford's Model T mass production", note: 'USA, 1908' },
      { rank: 64, name: 'Titanic sinks', note: 'Atlantic, 1912' },
      { rank: 65, name: 'World War I begins', note: 'Europe, 1914' },
      { rank: 66, name: 'Russian Revolution', note: 'Russia, 1917' },
      { rank: 67, name: 'Penicillin discovered', note: 'UK, 1928' },
      { rank: 68, name: 'Great Depression begins', note: 'Global, 1929' },
      { rank: 69, name: 'World War II begins', note: 'Global, 1939' },
      { rank: 70, name: 'First nuclear chain reaction achieved', note: 'USA, 1942' },
      { rank: 71, name: 'Antibiotics mass-produced', note: 'Global, 1940s' },
      { rank: 72, name: 'United Nations founded', note: 'Global, 1945' },
      { rank: 73, name: 'India gains independence', note: 'South Asia, 1947' },
      { rank: 74, name: "DNA's double helix structure discovered", note: 'UK, 1953' },
      { rank: 75, name: 'First human spaceflight, Yuri Gagarin', note: 'USSR, 1961' },
      { rank: 76, name: "Martin Luther King's \"I Have a Dream\" speech", note: 'USA, 1963' },
      { rank: 77, name: 'Apollo 11 Moon landing', note: 'USA, 1969' },
      { rank: 78, name: 'First email sent', note: 'USA, 1971' },
      { rank: 79, name: 'Personal computer revolution begins', note: 'USA, 1975-1977' },
      { rank: 80, name: 'Fall of the Berlin Wall', note: 'Germany, 1989' },
      { rank: 81, name: 'World Wide Web invented', note: 'CERN, 1989' },
      { rank: 82, name: 'Human Genome Project launched', note: 'Global, 1990' },
      { rank: 83, name: 'Soviet Union dissolves', note: 'Eurasia, 1991' },
      { rank: 84, name: 'Dolly the sheep cloned', note: 'UK, 1996' },
      { rank: 85, name: 'Internet goes public/commercial', note: 'Global, 1995' },
      { rank: 86, name: 'Google founded', note: 'USA, 1998' },
      { rank: 87, name: 'Human Genome Project completed', note: 'Global, 2003' },
      { rank: 88, name: 'Smartphone era begins (iPhone)', note: 'USA, 2007' },
      { rank: 89, name: 'Human genome sequencing costs plummet', note: 'Global, 2008' },
      { rank: 90, name: 'Higgs boson discovered', note: 'CERN, 2012' },
      { rank: 91, name: 'CRISPR gene editing breakthrough', note: 'Global, 2012-2015' },
      { rank: 92, name: 'Paris Agreement on climate signed', note: 'Global, 2015' },
      { rank: 93, name: 'First reusable orbital rocket landing', note: 'SpaceX, USA, 2015' },
      { rank: 94, name: 'First image of a black hole captured', note: 'Global, 2019' },
      { rank: 95, name: 'COVID-19 pandemic declared', note: 'Global, 2020' },
      { rank: 96, name: 'mRNA vaccines developed at record speed', note: 'Global, 2020' },
      { rank: 97, name: 'Renewable energy surpasses coal in some grids', note: 'Global, 2020s' },
      { rank: 98, name: 'James Webb Space Telescope begins observations', note: 'Global, 2022' },
      { rank: 99, name: 'Artemis program returns to the Moon (uncrewed test)', note: 'USA, 2022' },
      { rank: 100, name: 'Generative AI reaches mainstream adoption', note: 'Global, 2022-2023' },
    ],
  },
  {
    key: 'mountains',
    icon: Mountain,
    color: '#38bdf8',
    entries: [
      { rank: 1, name: 'Mount Everest', note: 'Nepal/China · 8,849m' },
      { rank: 2, name: 'K2', note: 'Pakistan/China · 8,611m' },
      { rank: 3, name: 'Kangchenjunga', note: 'Nepal/India · 8,586m' },
      { rank: 4, name: 'Lhotse', note: 'Nepal/China · 8,516m' },
      { rank: 5, name: 'Makalu', note: 'Nepal/China · 8,485m' },
      { rank: 6, name: 'Cho Oyu', note: 'Nepal/China · 8,188m' },
      { rank: 7, name: 'Dhaulagiri I', note: 'Nepal · 8,167m' },
      { rank: 8, name: 'Manaslu', note: 'Nepal · 8,163m' },
      { rank: 9, name: 'Nanga Parbat', note: 'Pakistan · 8,126m' },
      { rank: 10, name: 'Annapurna I', note: 'Nepal · 8,091m' },
      { rank: 11, name: 'Gasherbrum I', note: 'Pakistan/China · 8,080m' },
      { rank: 12, name: 'Broad Peak', note: 'Pakistan/China · 8,051m' },
      { rank: 13, name: 'Gasherbrum II', note: 'Pakistan/China · 8,035m' },
      { rank: 14, name: 'Shishapangma', note: 'China · 8,027m' },
      { rank: 15, name: 'Aconcagua', note: 'Argentina · 6,961m' },
      { rank: 16, name: 'Denali', note: 'USA · 6,190m' },
      { rank: 17, name: 'Kilimanjaro', note: 'Tanzania · 5,895m' },
      { rank: 18, name: 'Mount Elbrus', note: 'Russia · 5,642m' },
      { rank: 19, name: 'Vinson Massif', note: 'Antarctica · 4,892m' },
      { rank: 20, name: 'Puncak Jaya', note: 'Indonesia · 4,884m' },
      { rank: 21, name: 'Pico Cristóbal Colón', note: 'Colombia · 5,730m' },
      { rank: 22, name: 'Mount Ararat', note: 'Türkiye · 5,137m' },
      { rank: 23, name: 'Mount Logan', note: 'Canada · 5,959m' },
      { rank: 24, name: 'Pico de Orizaba', note: 'Mexico · 5,636m' },
      { rank: 25, name: 'Mount Kenya', note: 'Kenya · 5,199m' },
      { rank: 26, name: 'Mauna Kea', note: 'USA (Hawaii) · 4,207m' },
      { rank: 27, name: 'Mount Rainier', note: 'USA · 4,392m' },
      { rank: 28, name: 'Matterhorn', note: 'Switzerland/Italy · 4,478m' },
      { rank: 29, name: 'Mont Blanc', note: 'France/Italy · 4,809m' },
      { rank: 30, name: 'Mount Whitney', note: 'USA · 4,421m' },
    ],
  },
  {
    key: 'rivers',
    icon: Waves,
    color: '#2dd4bf',
    entries: [
      { rank: 1, name: 'Nile', note: 'Africa · ~6,650km' },
      { rank: 2, name: 'Amazon', note: 'South America · ~6,400km' },
      { rank: 3, name: 'Yangtze', note: 'China · ~6,300km' },
      { rank: 4, name: 'Mississippi–Missouri', note: 'USA · ~6,275km' },
      { rank: 5, name: 'Yenisei–Angara', note: 'Russia · ~5,539km' },
      { rank: 6, name: 'Yellow River (Huang He)', note: 'China · ~5,464km' },
      { rank: 7, name: 'Ob–Irtysh', note: 'Russia/Kazakhstan · ~5,410km' },
      { rank: 8, name: 'Congo', note: 'Africa · ~4,700km' },
      { rank: 9, name: 'Amur–Argun', note: 'Russia/China · ~4,444km' },
      { rank: 10, name: 'Lena', note: 'Russia · ~4,400km' },
      { rank: 11, name: 'Mekong', note: 'Southeast Asia · ~4,350km' },
      { rank: 12, name: 'Mackenzie', note: 'Canada · ~4,241km' },
      { rank: 13, name: 'Niger', note: 'West Africa · ~4,180km' },
      { rank: 14, name: 'Brahmaputra', note: 'Asia · ~3,969km' },
      { rank: 15, name: 'Murray–Darling', note: 'Australia · ~3,672km' },
      { rank: 16, name: 'Volga', note: 'Russia · ~3,531km' },
      { rank: 17, name: 'Madeira', note: 'South America · ~3,250km' },
      { rank: 18, name: 'Purus', note: 'South America · ~3,211km' },
      { rank: 19, name: 'Yukon', note: 'Canada/USA · ~3,190km' },
      { rank: 20, name: 'Indus', note: 'Asia · ~3,180km' },
      { rank: 21, name: 'Paraná', note: 'South America · ~4,880km' },
      { rank: 22, name: 'Rio Grande', note: 'USA/Mexico · ~3,051km' },
      { rank: 23, name: 'São Francisco', note: 'Brazil · ~2,914km' },
      { rank: 24, name: 'Danube', note: 'Europe · ~2,850km' },
      { rank: 25, name: 'Tocantins', note: 'Brazil · ~2,850km' },
      { rank: 26, name: 'Salween', note: 'Asia · ~2,815km' },
      { rank: 27, name: 'Euphrates', note: 'Middle East · ~2,800km' },
      { rank: 28, name: 'Ganges', note: 'South Asia · ~2,525km' },
      { rank: 29, name: 'Zambezi', note: 'Africa · ~2,574km' },
      { rank: 30, name: 'Amu Darya', note: 'Central Asia · ~2,400km' },
      { rank: 31, name: 'Orinoco', note: 'South America · ~2,140km' },
      { rank: 32, name: 'Syr Darya', note: 'Central Asia · ~2,212km' },
      { rank: 33, name: 'Colorado River', note: 'USA/Mexico · ~2,330km' },
      { rank: 34, name: 'Tigris', note: 'Middle East · ~1,900km' },
      { rank: 35, name: 'Columbia River', note: 'USA/Canada · ~2,000km' },
    ],
  },
  {
    key: 'buildings',
    icon: Building2,
    color: '#c084fc',
    entries: [
      { rank: 1, name: 'Burj Khalifa', note: 'Dubai · 828m' },
      { rank: 2, name: 'Merdeka 118', note: 'Kuala Lumpur · 679m' },
      { rank: 3, name: 'Shanghai Tower', note: 'Shanghai · 632m' },
      { rank: 4, name: 'Abraj Al-Bait Clock Tower', note: 'Mecca · 601m' },
      { rank: 5, name: 'Ping An Finance Center', note: 'Shenzhen · 599m' },
      { rank: 6, name: 'Lotte World Tower', note: 'Seoul · 555m' },
      { rank: 7, name: 'One World Trade Center', note: 'New York · 541m' },
      { rank: 8, name: 'Guangzhou CTF Finance Centre', note: 'Guangzhou · 530m' },
      { rank: 9, name: 'Tianjin CTF Finance Centre', note: 'Tianjin · 530m' },
      { rank: 10, name: 'CITIC Tower', note: 'Beijing · 528m' },
      { rank: 11, name: 'Taipei 101', note: 'Taipei · 508m' },
      { rank: 12, name: 'Shanghai World Financial Center', note: 'Shanghai · 492m' },
      { rank: 13, name: 'International Commerce Centre', note: 'Hong Kong · 484m' },
      { rank: 14, name: 'Central Park Tower', note: 'New York · 472m' },
      { rank: 15, name: 'Lakhta Center', note: 'St. Petersburg · 462m' },
      { rank: 16, name: 'Vincom Landmark 81', note: 'Ho Chi Minh City · 461m' },
      { rank: 17, name: 'Changsha IFS Tower T1', note: 'Changsha · 452m' },
      { rank: 18, name: 'Petronas Tower 1', note: 'Kuala Lumpur · 452m' },
      { rank: 19, name: 'Petronas Tower 2', note: 'Kuala Lumpur · 452m' },
      { rank: 20, name: 'Suzhou IFS', note: 'Suzhou · 450m' },
      { rank: 21, name: 'Zifeng Tower', note: 'Nanjing · 450m' },
      { rank: 22, name: 'The Exchange 106', note: 'Kuala Lumpur · 445m' },
      { rank: 23, name: 'KK100', note: 'Shenzhen · 442m' },
      { rank: 24, name: 'Willis Tower', note: 'Chicago · 442m' },
      { rank: 25, name: 'Guangzhou International Finance Center', note: 'Guangzhou · 439m' },
      { rank: 26, name: 'Wuhan Center Tower', note: 'Wuhan · 438m' },
      { rank: 27, name: 'One Vanderbilt', note: 'New York · 427m' },
      { rank: 28, name: 'Marina 101', note: 'Dubai · 425m' },
      { rank: 29, name: 'Trump International Hotel & Tower', note: 'Chicago · 423m' },
      { rank: 30, name: '432 Park Avenue', note: 'New York · 426m' },
      { rank: 31, name: 'Princess Tower', note: 'Dubai · 414m' },
      { rank: 32, name: 'Busan Lotte Town Tower', note: 'Busan · 411m' },
      { rank: 33, name: 'Al Hamra Tower', note: 'Kuwait City · 413m' },
      { rank: 34, name: '23 Marina', note: 'Dubai · 393m' },
      { rank: 35, name: '30 Hudson Yards', note: 'New York · 387m' },
      { rank: 36, name: 'Empire State Building', note: 'New York · 381m' },
      { rank: 37, name: 'Elite Residence', note: 'Dubai · 380m' },
      { rank: 38, name: 'Federation Tower (Vostok)', note: 'Moscow · 374m' },
      { rank: 39, name: 'Bank of America Tower', note: 'New York · 366m' },
      { rank: 40, name: 'One Bangkok Tower', note: 'Bangkok · 436m' },
      { rank: 41, name: 'Comcast Technology Center', note: 'Philadelphia · 342m' },
      { rank: 42, name: 'Wilshire Grand Center', note: 'Los Angeles · 335m' },
      { rank: 43, name: 'MahaNakhon', note: 'Bangkok · 314m' },
      { rank: 44, name: 'Keangnam Hanoi Landmark Tower', note: 'Hanoi · 336m' },
      { rank: 45, name: 'Eureka Tower', note: 'Melbourne · 297m' },
      { rank: 46, name: 'Australia 108', note: 'Melbourne · 316m' },
      { rank: 47, name: 'Q1 Tower', note: 'Gold Coast, Australia · 323m' },
      { rank: 48, name: 'Salesforce Tower', note: 'San Francisco · 326m' },
      { rank: 49, name: 'Torre Costanera', note: 'Santiago · 300m' },
      { rank: 50, name: 'Gran Torre Santiago', note: 'Santiago · 300m' },
      { rank: 51, name: 'Torre Reforma', note: 'Mexico City · 246m' },
      { rank: 52, name: 'Baiyoke Tower II', note: 'Bangkok · 304m' },
      { rank: 53, name: '63 Building', note: 'Seoul · 249m' },
      { rank: 54, name: 'Haeundae LCT The Sharp Landmark Tower', note: 'Busan · 412m' },
      { rank: 55, name: 'World One', note: 'Mumbai · 280m' },
    ],
  },
  {
    key: 'population',
    icon: Users2,
    color: '#34d399',
    entries: [
      { rank: 1, name: 'India', note: '~1.44B' },
      { rank: 2, name: 'China', note: '~1.41B' },
      { rank: 3, name: 'United States', note: '~340M' },
      { rank: 4, name: 'Indonesia', note: '~280M' },
      { rank: 5, name: 'Pakistan', note: '~250M' },
      { rank: 6, name: 'Nigeria', note: '~230M' },
      { rank: 7, name: 'Brazil', note: '~217M' },
      { rank: 8, name: 'Bangladesh', note: '~173M' },
      { rank: 9, name: 'Russia', note: '~144M' },
      { rank: 10, name: 'Mexico', note: '~130M' },
      { rank: 11, name: 'Ethiopia', note: '~127M' },
      { rank: 12, name: 'Japan', note: '~123M' },
      { rank: 13, name: 'Philippines', note: '~118M' },
      { rank: 14, name: 'Egypt', note: '~116M' },
      { rank: 15, name: 'DR Congo', note: '~102M' },
      { rank: 16, name: 'Vietnam', note: '~100M' },
      { rank: 17, name: 'Iran', note: '~89M' },
      { rank: 18, name: 'Türkiye', note: '~87M' },
      { rank: 19, name: 'Germany', note: '~84M' },
      { rank: 20, name: 'Thailand', note: '~72M' },
      { rank: 21, name: 'United Kingdom', note: '~68M' },
      { rank: 22, name: 'Tanzania', note: '~67M' },
      { rank: 23, name: 'France', note: '~66M' },
      { rank: 24, name: 'South Africa', note: '~60M' },
      { rank: 25, name: 'Italy', note: '~59M' },
      { rank: 26, name: 'Kenya', note: '~56M' },
      { rank: 27, name: 'Myanmar', note: '~55M' },
      { rank: 28, name: 'Colombia', note: '~52M' },
      { rank: 29, name: 'South Korea', note: '~52M' },
      { rank: 30, name: 'Uganda', note: '~48M' },
      { rank: 31, name: 'Sudan', note: '~48M' },
      { rank: 32, name: 'Spain', note: '~48M' },
      { rank: 33, name: 'Algeria', note: '~46M' },
      { rank: 34, name: 'Argentina', note: '~46M' },
      { rank: 35, name: 'Iraq', note: '~45M' },
      { rank: 36, name: 'Afghanistan', note: '~42M' },
      { rank: 37, name: 'Canada', note: '~39M' },
      { rank: 38, name: 'Poland', note: '~38M' },
      { rank: 39, name: 'Morocco', note: '~38M' },
      { rank: 40, name: 'Yemen', note: '~34M' },
      { rank: 41, name: 'Angola', note: '~36M' },
      { rank: 42, name: 'Ukraine', note: '~36M' },
      { rank: 43, name: 'Uzbekistan', note: '~35M' },
      { rank: 44, name: 'Malaysia', note: '~34M' },
      { rank: 45, name: 'Ghana', note: '~34M' },
      { rank: 46, name: 'Peru', note: '~34M' },
      { rank: 47, name: 'Saudi Arabia', note: '~36M' },
      { rank: 48, name: 'Mozambique', note: '~33M' },
      { rank: 49, name: 'Madagascar', note: '~30M' },
      { rank: 50, name: 'Nepal', note: '~30M' },
      { rank: 51, name: 'Venezuela', note: '~28M' },
      { rank: 52, name: 'Ivory Coast', note: '~29M' },
      { rank: 53, name: 'Cameroon', note: '~28M' },
      { rank: 54, name: 'Australia', note: '~26M' },
      { rank: 55, name: 'Niger', note: '~27M' },
      { rank: 56, name: 'North Korea', note: '~26M' },
      { rank: 57, name: 'Sri Lanka', note: '~22M' },
      { rank: 58, name: 'Mali', note: '~23M' },
      { rank: 59, name: 'Burkina Faso', note: '~23M' },
      { rank: 60, name: 'Syria', note: '~23M' },
      { rank: 61, name: 'Malawi', note: '~21M' },
      { rank: 62, name: 'Chile', note: '~20M' },
      { rank: 63, name: 'Kazakhstan', note: '~20M' },
      { rank: 64, name: 'Zambia', note: '~20M' },
      { rank: 65, name: 'Ecuador', note: '~18M' },
      { rank: 66, name: 'Netherlands', note: '~18M' },
      { rank: 67, name: 'Somalia', note: '~18M' },
      { rank: 68, name: 'Senegal', note: '~18M' },
      { rank: 69, name: 'Chad', note: '~18M' },
      { rank: 70, name: 'Cambodia', note: '~17M' },
      { rank: 71, name: 'Guatemala', note: '~18M' },
      { rank: 72, name: 'Zimbabwe', note: '~16M' },
      { rank: 73, name: 'Guinea', note: '~14M' },
      { rank: 74, name: 'Rwanda', note: '~14M' },
      { rank: 75, name: 'Benin', note: '~13M' },
      { rank: 76, name: 'Burundi', note: '~13M' },
      { rank: 77, name: 'South Sudan', note: '~11M' },
      { rank: 78, name: 'Tunisia', note: '~12M' },
      { rank: 79, name: 'Bolivia', note: '~12M' },
      { rank: 80, name: 'Belgium', note: '~12M' },
      { rank: 81, name: 'Cuba', note: '~11M' },
      { rank: 82, name: 'Haiti', note: '~11M' },
      { rank: 83, name: 'Dominican Republic', note: '~11M' },
      { rank: 84, name: 'Jordan', note: '~11M' },
      { rank: 85, name: 'United Arab Emirates', note: '~10M' },
      { rank: 86, name: 'Sweden', note: '~10M' },
      { rank: 87, name: 'Czechia', note: '~11M' },
      { rank: 88, name: 'Greece', note: '~10M' },
      { rank: 89, name: 'Portugal', note: '~10M' },
      { rank: 90, name: 'Papua New Guinea', note: '~10M' },
      { rank: 91, name: 'Azerbaijan', note: '~10M' },
      { rank: 92, name: 'Honduras', note: '~10M' },
      { rank: 93, name: 'Hungary', note: '~10M' },
      { rank: 94, name: 'Tajikistan', note: '~10M' },
      { rank: 95, name: 'Belarus', note: '~9M' },
      { rank: 96, name: 'Austria', note: '~9M' },
      { rank: 97, name: 'Israel', note: '~9M' },
      { rank: 98, name: 'Switzerland', note: '~9M' },
      { rank: 99, name: 'Togo', note: '~9M' },
      { rank: 100, name: 'Sierra Leone', note: '~8M' },
    ],
  },
  {
    key: 'filmBoxOffice',
    icon: Clapperboard,
    color: '#fb7185',
    entries: [
      { rank: 1, name: 'Avatar', note: '2009 · ~$2.92B' },
      { rank: 2, name: 'Avengers: Endgame', note: '2019 · ~$2.80B' },
      { rank: 3, name: 'Avatar: The Way of Water', note: '2022 · ~$2.32B' },
      { rank: 4, name: 'Titanic', note: '1997 · ~$2.26B' },
      { rank: 5, name: 'Star Wars: The Force Awakens', note: '2015 · ~$2.07B' },
      { rank: 6, name: 'Avengers: Infinity War', note: '2018 · ~$2.05B' },
      { rank: 7, name: 'Spider-Man: No Way Home', note: '2021 · ~$1.92B' },
      { rank: 8, name: 'Inside Out 2', note: '2024 · ~$1.70B' },
      { rank: 9, name: 'Jurassic World', note: '2015 · ~$1.67B' },
      { rank: 10, name: 'The Lion King', note: '2019 · ~$1.66B' },
      { rank: 11, name: 'The Avengers', note: '2012 · ~$1.52B' },
      { rank: 12, name: 'Furious 7', note: '2015 · ~$1.52B' },
      { rank: 13, name: 'Top Gun: Maverick', note: '2022 · ~$1.49B' },
      { rank: 14, name: 'Frozen II', note: '2019 · ~$1.45B' },
      { rank: 15, name: 'Barbie', note: '2023 · ~$1.45B' },
      { rank: 16, name: 'Avengers: Age of Ultron', note: '2015 · ~$1.40B' },
      { rank: 17, name: 'The Super Mario Bros. Movie', note: '2023 · ~$1.36B' },
      { rank: 18, name: 'Black Panther', note: '2018 · ~$1.35B' },
      { rank: 19, name: 'Harry Potter and the Deathly Hallows – Part 2', note: '2011 · ~$1.34B' },
      { rank: 20, name: 'Star Wars: The Last Jedi', note: '2017 · ~$1.33B' },
      { rank: 21, name: 'Jurassic World: Fallen Kingdom', note: '2018 · ~$1.31B' },
      { rank: 22, name: 'Frozen', note: '2013 · ~$1.28B' },
      { rank: 23, name: 'Beauty and the Beast', note: '2017 · ~$1.27B' },
      { rank: 24, name: 'Incredibles 2', note: '2018 · ~$1.24B' },
      { rank: 25, name: 'The Fate of the Furious', note: '2017 · ~$1.24B' },
      { rank: 26, name: 'Iron Man 3', note: '2013 · ~$1.21B' },
      { rank: 27, name: 'Minions', note: '2015 · ~$1.16B' },
      { rank: 28, name: 'Captain America: Civil War', note: '2016 · ~$1.15B' },
      { rank: 29, name: 'Aquaman', note: '2018 · ~$1.15B' },
      { rank: 30, name: 'The Lord of the Rings: The Return of the King', note: '2003 · ~$1.15B' },
      { rank: 31, name: 'Spider-Man: Far From Home', note: '2019 · ~$1.13B' },
      { rank: 32, name: 'Captain Marvel', note: '2019 · ~$1.13B' },
      { rank: 33, name: 'Transformers: Dark of the Moon', note: '2011 · ~$1.12B' },
      { rank: 34, name: 'Skyfall', note: '2012 · ~$1.11B' },
      { rank: 35, name: 'Transformers: Age of Extinction', note: '2014 · ~$1.10B' },
      { rank: 36, name: 'The Dark Knight Rises', note: '2012 · ~$1.08B' },
      { rank: 37, name: 'Toy Story 4', note: '2019 · ~$1.07B' },
      { rank: 38, name: 'Pirates of the Caribbean: Dead Man’s Chest', note: '2006 · ~$1.07B' },
      { rank: 39, name: 'Joker', note: '2019 · ~$1.07B' },
      { rank: 40, name: 'Star Wars: Episode I – The Phantom Menace', note: '1999 · ~$1.03B' },
      { rank: 41, name: 'Toy Story 3', note: '2010 · ~$1.07B' },
      { rank: 42, name: 'Pirates of the Caribbean: On Stranger Tides', note: '2011 · ~$1.05B' },
      { rank: 43, name: 'Rogue One: A Star Wars Story', note: '2016 · ~$1.06B' },
      { rank: 44, name: 'Aladdin', note: '2019 · ~$1.05B' },
      { rank: 45, name: 'Despicable Me 3', note: '2017 · ~$1.03B' },
      { rank: 46, name: 'Finding Dory', note: '2016 · ~$1.03B' },
      { rank: 47, name: 'Alice in Wonderland', note: '2010 · ~$1.03B' },
      { rank: 48, name: 'Zootopia', note: '2016 · ~$1.02B' },
      { rank: 49, name: 'The Dark Knight', note: '2008 · ~$1.01B' },
      { rank: 50, name: 'Jurassic Park', note: '1993 · ~$1.03B' },
    ],
  },
];
