import {
  Landmark,
  TrendingUp,
  Trophy,
  Mountain,
  Waves,
  Building2,
  Users2,
  Clapperboard,
  PlaySquare,
  Gamepad2,
  Disc3,
  Medal,
  type LucideIcon,
} from 'lucide-react';

// The 핫이슈 tab's "하이브리드 테마 랭킹 위젯" (owner instruction 2026-09-04, deepened
// 2026-09-04, retitled + expanded 2026-09-04 round 2 into "실시간 핫이슈 랭킹"):
// a row of theme chips sitting below HotIssueNewsList's live feed. Tapping a
// chip expands its top-10 countdown; "11~50위 보기" / "51~100위 보기"
// progressively widen the visible window (LOAD_MORE_TIERS). Every ranked row
// here is a factual, independently verifiable snapshot (heritage-site counts,
// elevations, river lengths, nominal GDP, box-office gross, population,
// building height, historical milestones, video view counts, esports prize
// pools, album sales, individual human records) -- deliberately NOT padded
// with invented filler once real, confidently-sourceable data runs out, so
// `entries.length` legitimately varies per theme (20-100) and the widget
// shows a "collectingMore" state past it rather than fabricate ranks nobody
// can verify. Depth per theme reflects genuine confidence, not a mechanical
// round number: country-level statistics (population, GDP, heritage-site
// counts) extend furthest since misordering two similarly-sized economies is
// a minor precision issue, while uniquely-named structures/records (buildings,
// mountains, rivers, videos, esports titles, albums, human records) stay
// shallower because a wrong/duplicated proper noun -- or a fast-moving
// personal/viewership record -- is a much more visible error.
// Entry labels stay in English across every locale by design (proper nouns /
// figures a Korean, Thai, or Estonian visitor reads identically) -- only the
// theme title/description and the widget's chrome strings are localized
// (messages/*.json -> `GlobalRankings` namespace). `detail` (owner
// instruction 2026-09-04 round 2: rank-1~20 drilldown popups) follows the
// same convention -- an untranslated, English one-liner shown when a visitor
// taps into a specific rank for a fuller explanation than the compact
// name/note row gives. It is curated for ranks 1-20 of every theme (the
// ranks the popup interaction actually exposes); ranks beyond 20 fall back to
// a plain "name · note" render in the entry-detail popup instead of a
// fabricated blurb.

export type GlobalRankingThemeKey =
  | 'heritage'
  | 'gdp'
  | 'records'
  | 'mountains'
  | 'rivers'
  | 'buildings'
  | 'population'
  | 'filmBoxOffice'
  | 'youtubeViews'
  | 'esportsEarnings'
  | 'albumSales'
  | 'humanRecords';

export interface GlobalRankingEntry {
  /** Rank position, 1-indexed. */
  rank: number;
  /** The ranked subject -- a country, structure, film, or milestone. Kept
   *  untranslated (see file banner). */
  name: string;
  /** Short factual qualifier shown beside the name (figure, year, location). */
  note: string;
  /** Optional one-line elaboration shown in the entry-detail popup, curated
   *  for ranks 1-20 (see file banner). Kept untranslated like name/note. */
  detail?: string;
}

export interface GlobalRankingTheme {
  key: GlobalRankingThemeKey;
  icon: LucideIcon;
  color: string;
  entries: GlobalRankingEntry[];
}

/** Progressive reveal windows the "11~50위 보기" / "51~100위 보기" buttons step
 *  through -- capped per-theme at `entries.length` (see GlobalThemeRankings). */
export const LOAD_MORE_TIERS = [10, 50, 100] as const;

export const GLOBAL_RANKING_THEMES: GlobalRankingTheme[] = [
  {
    key: 'heritage',
    icon: Landmark,
    color: '#facc15',
    entries: [
      { rank: 1, name: 'Italy', note: '60 sites', detail: "Italy's dense concentration of Renaissance cities, Roman ruins, and historic centers gives it more UNESCO-listed sites than any other nation." },
      { rank: 2, name: 'China', note: '59 sites', detail: "From the Great Wall to ancient capitals, China's imperial-era architecture and natural wonders anchor its heritage count." },
      { rank: 3, name: 'Germany', note: '54 sites', detail: "Germany's cathedrals, industrial-heritage complexes, and Hanseatic old towns make up its 54 listed sites." },
      { rank: 4, name: 'France', note: '53 sites', detail: "France's palaces, cathedrals, and prehistoric cave-art sites carry its heritage listing." },
      { rank: 5, name: 'Spain', note: '50 sites', detail: "Spain's Moorish palaces, the Camino de Santiago route, and historic quarters drive its heritage total." },
      { rank: 6, name: 'India', note: '43 sites', detail: "India's Mughal monuments, ancient temple complexes, and colonial-era sites make up its 43 listings." },
      { rank: 7, name: 'Mexico', note: '35 sites', detail: "Mexico's pre-Columbian pyramids and colonial cities account for its heritage count." },
      { rank: 8, name: 'United Kingdom', note: '34 sites', detail: "The UK's castles, industrial landmarks, and prehistoric monuments like Stonehenge fill its list." },
      { rank: 9, name: 'Russia', note: '32 sites', detail: "Russia's Kremlin, historic monasteries, and natural reserves make up its heritage sites." },
      { rank: 10, name: 'Iran', note: '28 sites', detail: "Iran's Persian palaces, mosques, and ancient cities trace back millennia." },
      { rank: 11, name: 'Japan', note: '26 sites', detail: "Japan's shrines, castles, and the Hiroshima Peace Memorial anchor its heritage sites." },
      { rank: 12, name: 'United States', note: '26 sites', detail: "The US list spans natural wonders like Yellowstone to historic independence-era sites." },
      { rank: 13, name: 'Brazil', note: '23 sites', detail: "Brazil's colonial towns and Amazon reserves make up its heritage total." },
      { rank: 14, name: 'Australia', note: '20 sites', detail: "Australia's Great Barrier Reef and Sydney Opera House headline its listings." },
      { rank: 15, name: 'Canada', note: '20 sites', detail: "Canada's national parks and historic districts fill out its heritage sites." },
      { rank: 16, name: 'Türkiye', note: '21 sites', detail: "Türkiye bridges continents with sites like Hagia Sophia and Cappadocia's rock formations." },
      { rank: 17, name: 'Greece', note: '19 sites', detail: "Greece's ancient Acropolis and archaeological sites anchor Western civilization's heritage record." },
      { rank: 18, name: 'Portugal', note: '17 sites', detail: "Portugal's monasteries and historic port cities make up its list." },
      { rank: 19, name: 'Poland', note: '17 sites', detail: "Poland's historic old towns and the Auschwitz memorial site are among its listings." },
      { rank: 20, name: 'South Korea', note: '16 sites', detail: "South Korea's royal palaces and Buddhist temple complexes make up its 16 sites." },
      { rank: 21, name: 'Czechia', note: '16 sites' },
      { rank: 22, name: 'Belgium', note: '15 sites' },
      { rank: 23, name: 'Sweden', note: '15 sites' },
      { rank: 24, name: 'Switzerland', note: '13 sites' },
      { rank: 25, name: 'Netherlands', note: '13 sites' },
      { rank: 26, name: 'Peru', note: '13 sites' },
      { rank: 27, name: 'Austria', note: '12 sites' },
      { rank: 28, name: 'Argentina', note: '12 sites' },
      { rank: 29, name: 'Croatia', note: '11 sites' },
      { rank: 30, name: 'Denmark', note: '11 sites' },
      { rank: 31, name: 'Indonesia', note: '10 sites' },
      { rank: 32, name: 'Bulgaria', note: '10 sites' },
      { rank: 33, name: 'South Africa', note: '10 sites' },
      { rank: 34, name: 'Israel', note: '9 sites' },
      { rank: 35, name: 'Hungary', note: '9 sites' },
      { rank: 36, name: 'Ethiopia', note: '9 sites' },
      { rank: 37, name: 'Morocco', note: '9 sites' },
      { rank: 38, name: 'Colombia', note: '9 sites' },
      { rank: 39, name: 'Cuba', note: '9 sites' },
      { rank: 40, name: 'Romania', note: '9 sites' },
      { rank: 41, name: 'Uzbekistan', note: '9 sites' },
      { rank: 42, name: 'Egypt', note: '7 sites' },
      { rank: 43, name: 'Tunisia', note: '8 sites' },
      { rank: 44, name: 'Vietnam', note: '8 sites' },
      { rank: 45, name: 'Chile', note: '7 sites' },
      { rank: 46, name: 'Thailand', note: '7 sites' },
      { rank: 47, name: 'Sri Lanka', note: '8 sites' },
      { rank: 48, name: 'Finland', note: '7 sites' },
      { rank: 49, name: 'Slovakia', note: '8 sites' },
      { rank: 50, name: 'Ukraine', note: '8 sites' },
      { rank: 51, name: 'Norway', note: '8 sites' },
      { rank: 52, name: 'Philippines', note: '6 sites' },
      { rank: 53, name: 'Kazakhstan', note: '6 sites' },
      { rank: 54, name: 'Mongolia', note: '6 sites' },
      { rank: 55, name: 'Pakistan', note: '6 sites' },
      { rank: 56, name: 'Slovenia', note: '5 sites' },
      { rank: 57, name: 'Serbia', note: '5 sites' },
      { rank: 58, name: 'Lithuania', note: '5 sites' },
      { rank: 59, name: 'Bolivia', note: '7 sites' },
      { rank: 60, name: 'Ecuador', note: '5 sites' },
      { rank: 61, name: 'Senegal', note: '7 sites' },
      { rank: 62, name: 'Ivory Coast', note: '5 sites' },
      { rank: 63, name: 'Zimbabwe', note: '5 sites' },
      { rank: 64, name: 'Tanzania', note: '7 sites' },
      { rank: 65, name: 'DR Congo', note: '5 sites' },
      { rank: 66, name: 'Georgia', note: '4 sites' },
      { rank: 67, name: 'Belarus', note: '4 sites' },
      { rank: 68, name: 'Nepal', note: '4 sites' },
      { rank: 69, name: 'Malaysia', note: '4 sites' },
      { rank: 70, name: 'Panama', note: '5 sites' },
    ],
  },
  {
    key: 'gdp',
    icon: TrendingUp,
    color: '#60a5fa',
    entries: [
      { rank: 1, name: 'United States', note: '~$27T nominal GDP', detail: "The world's largest economy, driven by services, technology, and consumer spending." },
      { rank: 2, name: 'China', note: '~$18T', detail: "The world's manufacturing powerhouse and second-largest economy by nominal GDP." },
      { rank: 3, name: 'Germany', note: '~$4.5T', detail: "Europe's largest economy, anchored by advanced manufacturing and exports." },
      { rank: 4, name: 'Japan', note: '~$4.1T', detail: "A global leader in electronics and automotive manufacturing." },
      { rank: 5, name: 'India', note: '~$3.9T', detail: "The world's fastest-growing major economy, driven by services and a vast domestic market." },
      { rank: 6, name: 'United Kingdom', note: '~$3.3T', detail: "A global financial-services hub centered on London." },
      { rank: 7, name: 'France', note: '~$3.0T', detail: "A diversified economy strong in luxury goods, aerospace, and tourism." },
      { rank: 8, name: 'Brazil', note: '~$2.3T', detail: "Latin America's largest economy, rich in agriculture and commodities." },
      { rank: 9, name: 'Italy', note: '~$2.3T', detail: "Known for manufacturing, fashion, and a large small-business sector." },
      { rank: 10, name: 'Canada', note: '~$2.1T', detail: "A resource-rich economy with strong ties to US trade." },
      { rank: 11, name: 'Russia', note: '~$2.0T', detail: "An economy heavily weighted toward energy exports." },
      { rank: 12, name: 'South Korea', note: '~$1.8T', detail: "A technology and manufacturing powerhouse led by global conglomerates." },
      { rank: 13, name: 'Australia', note: '~$1.7T', detail: "A resource-export economy with strong mining and agriculture sectors." },
      { rank: 14, name: 'Spain', note: '~$1.6T', detail: "A tourism- and services-driven economy within the Eurozone." },
      { rank: 15, name: 'Mexico', note: '~$1.5T', detail: "A major manufacturing hub tightly integrated with North American supply chains." },
      { rank: 16, name: 'Indonesia', note: '~$1.4T', detail: "Southeast Asia's largest economy, rich in natural resources." },
      { rank: 17, name: 'Netherlands', note: '~$1.1T', detail: "A trade and logistics hub anchoring European commerce." },
      { rank: 18, name: 'Saudi Arabia', note: '~$1.1T', detail: "The world's largest oil exporter, diversifying under Vision 2030." },
      { rank: 19, name: 'Türkiye', note: '~$1.1T', detail: "A manufacturing and trade bridge between Europe and Asia." },
      { rank: 20, name: 'Switzerland', note: '~$0.9T', detail: "A global hub for banking, pharmaceuticals, and precision manufacturing." },
      { rank: 21, name: 'Poland', note: '~$0.85T' },
      { rank: 22, name: 'Taiwan', note: '~$0.8T' },
      { rank: 23, name: 'Belgium', note: '~$0.65T' },
      { rank: 24, name: 'Argentina', note: '~$0.64T' },
      { rank: 25, name: 'Sweden', note: '~$0.59T' },
      { rank: 26, name: 'Ireland', note: '~$0.56T' },
      { rank: 27, name: 'Israel', note: '~$0.54T' },
      { rank: 28, name: 'United Arab Emirates', note: '~$0.53T' },
      { rank: 29, name: 'Thailand', note: '~$0.53T' },
      { rank: 30, name: 'Singapore', note: '~$0.5T' },
      { rank: 31, name: 'Nigeria', note: '~$0.48T' },
      { rank: 32, name: 'Norway', note: '~$0.48T' },
      { rank: 33, name: 'Austria', note: '~$0.47T' },
      { rank: 34, name: 'Egypt', note: '~$0.45T' },
      { rank: 35, name: 'Philippines', note: '~$0.44T' },
      { rank: 36, name: 'Bangladesh', note: '~$0.44T' },
      { rank: 37, name: 'Vietnam', note: '~$0.43T' },
      { rank: 38, name: 'Malaysia', note: '~$0.43T' },
      { rank: 39, name: 'Denmark', note: '~$0.41T' },
      { rank: 40, name: 'Colombia', note: '~$0.38T' },
      { rank: 41, name: 'Romania', note: '~$0.35T' },
      { rank: 42, name: 'Chile', note: '~$0.35T' },
      { rank: 43, name: 'Czechia', note: '~$0.34T' },
      { rank: 44, name: 'Pakistan', note: '~$0.34T' },
      { rank: 45, name: 'Iraq', note: '~$0.3T' },
      { rank: 46, name: 'Portugal', note: '~$0.28T' },
      { rank: 47, name: 'Peru', note: '~$0.27T' },
      { rank: 48, name: 'New Zealand', note: '~$0.26T' },
      { rank: 49, name: 'Kazakhstan', note: '~$0.26T' },
      { rank: 50, name: 'Qatar', note: '~$0.22T' },
      { rank: 51, name: 'Hungary', note: '~$0.21T' },
      { rank: 52, name: 'Ukraine', note: '~$0.18T' },
      { rank: 53, name: 'Kuwait', note: '~$0.16T' },
      { rank: 54, name: 'Ethiopia', note: '~$0.16T' },
      { rank: 55, name: 'Morocco', note: '~$0.15T' },
      { rank: 56, name: 'Dominican Republic', note: '~$0.13T' },
      { rank: 57, name: 'Guatemala', note: '~$0.11T' },
      { rank: 58, name: 'Oman', note: '~$0.11T' },
      { rank: 59, name: 'Bulgaria', note: '~$0.1T' },
      { rank: 60, name: 'Kenya', note: '~$0.12T' },
      { rank: 61, name: 'Slovakia', note: '~$0.13T' },
      { rank: 62, name: 'Ecuador', note: '~$0.12T' },
      { rank: 63, name: 'Angola', note: '~$0.1T' },
      { rank: 64, name: 'Uzbekistan', note: '~$0.09T' },
      { rank: 65, name: 'DR Congo', note: '~$0.07T' },
      { rank: 66, name: 'Sri Lanka', note: '~$0.085T' },
      { rank: 67, name: 'Myanmar', note: '~$0.065T' },
      { rank: 68, name: 'Luxembourg', note: '~$0.085T' },
      { rank: 69, name: 'Panama', note: '~$0.08T' },
      { rank: 70, name: 'Costa Rica', note: '~$0.075T' },
    ],
  },
  {
    key: 'records',
    icon: Trophy,
    color: '#e879f9',
    entries: [
      { rank: 1, name: 'Cuneiform script invented', note: 'Sumer, c. 3400 BCE', detail: "The earliest known writing system, used first for administrative record-keeping in Sumer." },
      { rank: 2, name: 'Egyptian hieroglyphic writing emerges', note: 'Egypt, c. 3200 BCE', detail: "A parallel early writing system that shaped Egyptian religious and state records." },
      { rank: 3, name: 'The wheel adopted for transport', note: 'Mesopotamia, c. 3500 BCE', detail: "One of humanity's most transformative inventions, revolutionizing transport and technology." },
      { rank: 4, name: 'Great Pyramid of Giza completed', note: 'Egypt, c. 2560 BCE', detail: "The last-standing wonder of the ancient world, built as a pharaoh's tomb." },
      { rank: 5, name: 'Bronze Age metallurgy spreads', note: 'Near East, c. 3300 BCE', detail: "Bronze tools and weapons reshaped warfare, agriculture, and trade networks." },
      { rank: 6, name: 'Indus Valley Civilization cities flourish', note: 'South Asia, c. 2500 BCE', detail: "One of the world's earliest urban civilizations, with advanced sanitation and planning." },
      { rank: 7, name: 'Code of Hammurabi inscribed', note: 'Babylon, c. 1754 BCE', detail: "One of the earliest written legal codes, establishing the principle of codified law." },
      { rank: 8, name: 'Iron Age begins', note: 'Anatolia, c. 1200 BCE', detail: "Iron tools and weapons succeeded bronze, reshaping economies and warfare." },
      { rank: 9, name: 'Phoenician alphabet spreads', note: 'Mediterranean, c. 1050 BCE', detail: "The ancestor of most modern alphabets, spread through Mediterranean trade." },
      { rank: 10, name: 'Great Wall of China begun', note: 'China, 7th century BCE', detail: "A defensive megastructure begun to protect against northern incursions." },
      { rank: 11, name: 'First Olympic Games held', note: 'Greece, 776 BCE', detail: "The origin of organized international athletic competition." },
      { rank: 12, name: 'Buddhism founded', note: 'India, c. 5th century BCE', detail: "One of the world's major religions, shaping philosophy across Asia." },
      { rank: 13, name: 'Library of Alexandria founded', note: 'Egypt, c. 285 BCE', detail: "Antiquity's greatest center of scholarship and recorded knowledge." },
      { rank: 14, name: "Confucius's teachings recorded", note: 'China, 5th century BCE', detail: "His teachings shaped East Asian ethics, governance, and education for millennia." },
      { rank: 15, name: 'Roman Republic established', note: 'Rome, 509 BCE', detail: "Its governance model influenced constitutional systems for over two millennia." },
      { rank: 16, name: 'Qin Shi Huang unifies China', note: 'China, 221 BCE', detail: "Created the first unified Chinese empire, standardizing writing and measures." },
      { rank: 17, name: "Julius Caesar's Rome", note: 'Rome, 1st century BCE', detail: "A pivotal era that reshaped Rome from republic toward empire." },
      { rank: 18, name: 'Paper invented', note: 'China, c. 105 CE', detail: "Revolutionized the recording and spread of information worldwide." },
      { rank: 19, name: 'Roman Empire reaches its height', note: 'Rome, 2nd century CE', detail: "Rome's territorial peak connected trade and culture across three continents." },
      { rank: 20, name: 'Silk Road trade networks flourish', note: 'Eurasia, 1st-2nd century CE', detail: "Connected East and West, exchanging goods, ideas, and technology for centuries." },
      { rank: 21, name: 'Constantine legalizes Christianity', note: 'Rome, 313 CE' },
      { rank: 22, name: 'Fall of the Western Roman Empire', note: 'Europe, 476 CE' },
      { rank: 23, name: 'Islam founded', note: 'Arabia, 7th century CE' },
      { rank: 24, name: 'Tang Dynasty golden age', note: 'China, 7th-9th century CE' },
      { rank: 25, name: 'Charlemagne crowned Holy Roman Emperor', note: 'Europe, 800 CE' },
      { rank: 26, name: 'Great Library of Baghdad (House of Wisdom) flourishes', note: 'Abbasid Caliphate, 9th century' },
      { rank: 27, name: 'Printing with movable type (Bi Sheng)', note: 'China, c. 1040' },
      { rank: 28, name: 'Great Schism splits Christianity', note: 'Europe, 1054' },
      { rank: 29, name: 'Compass adopted for navigation', note: 'China, 11th century' },
      { rank: 30, name: 'University of Bologna founded, first modern university', note: 'Italy, 1088' },
      { rank: 31, name: 'Angkor Wat constructed', note: 'Khmer Empire, 12th century' },
      { rank: 32, name: 'Magna Carta signed', note: 'England, 1215' },
      { rank: 33, name: 'Mongol Empire at its peak', note: 'Eurasia, 13th century' },
      { rank: 34, name: "Marco Polo's travels to China", note: 'Asia, 1271-1295' },
      { rank: 35, name: 'Black Death pandemic', note: 'Eurasia, 1347-1351' },
      { rank: 36, name: "Gutenberg's printing press", note: 'Germany, c. 1440' },
      { rank: 37, name: 'Fall of Constantinople', note: 'Byzantium, 1453' },
      { rank: 38, name: 'Columbus reaches the Americas', note: 'Atlantic, 1492' },
      { rank: 39, name: 'Vasco da Gama reaches India by sea', note: 'Indian Ocean, 1498' },
      { rank: 40, name: "Leonardo da Vinci's Renaissance works", note: 'Italy, late 15th century' },
      { rank: 41, name: 'Copernicus proposes heliocentrism', note: 'Poland, 1543' },
      { rank: 42, name: "Magellan's expedition circumnavigates the globe", note: 'Global, 1522' },
      { rank: 43, name: "Shakespeare's plays performed", note: 'England, late 16th century' },
      { rank: 44, name: "Galileo's telescope observations", note: 'Italy, 1609' },
      { rank: 45, name: "Newton's Principia Mathematica", note: 'England, 1687' },
      { rank: 46, name: 'Vaccination pioneered by Edward Jenner', note: 'England, 1796' },
      { rank: 47, name: 'Industrial Revolution begins', note: 'England, 1760s' },
      { rank: 48, name: 'American Declaration of Independence', note: 'USA, 1776' },
      { rank: 49, name: 'French Revolution begins', note: 'France, 1789' },
      { rank: 50, name: 'First steam locomotive runs', note: 'England, 1804' },
      { rank: 51, name: "Napoleon's Napoleonic Code enacted", note: 'France, 1804' },
      { rank: 52, name: 'Steam-powered factories transform textiles', note: 'England, 1780s' },
      { rank: 53, name: 'Darwin publishes On the Origin of Species', note: 'England, 1859' },
      { rank: 54, name: 'Transatlantic telegraph cable completed', note: 'Atlantic, 1866' },
      { rank: 55, name: 'Suez Canal opens', note: 'Egypt, 1869' },
      { rank: 56, name: 'Alexander Graham Bell patents the telephone', note: 'USA, 1876' },
      { rank: 57, name: "Edison's practical incandescent light bulb", note: 'USA, 1879' },
      { rank: 58, name: 'Eiffel Tower completed', note: 'France, 1889' },
      { rank: 59, name: 'First modern Olympic Games', note: 'Greece, 1896' },
      { rank: 60, name: 'Suffrage movements win women the vote', note: 'Global, 1893-1920' },
      { rank: 61, name: "Wright brothers' first powered flight", note: 'USA, 1903' },
      { rank: 62, name: 'Einstein publishes special relativity', note: 'Germany, 1905' },
      { rank: 63, name: "Ford's Model T mass production", note: 'USA, 1908' },
      { rank: 64, name: 'Titanic sinks', note: 'Atlantic, 1912' },
      { rank: 65, name: 'World War I begins', note: 'Europe, 1914' },
      { rank: 66, name: 'Russian Revolution', note: 'Russia, 1917' },
      { rank: 67, name: 'Penicillin discovered', note: 'UK, 1928' },
      { rank: 68, name: 'Great Depression begins', note: 'Global, 1929' },
      { rank: 69, name: 'World War II begins', note: 'Global, 1939' },
      { rank: 70, name: 'First nuclear chain reaction achieved', note: 'USA, 1942' },
      { rank: 71, name: 'Antibiotics mass-produced', note: 'Global, 1940s' },
      { rank: 72, name: 'United Nations founded', note: 'Global, 1945' },
      { rank: 73, name: 'India gains independence', note: 'South Asia, 1947' },
      { rank: 74, name: "DNA's double helix structure discovered", note: 'UK, 1953' },
      { rank: 75, name: 'First human spaceflight, Yuri Gagarin', note: 'USSR, 1961' },
      { rank: 76, name: "Martin Luther King's \"I Have a Dream\" speech", note: 'USA, 1963' },
      { rank: 77, name: 'Apollo 11 Moon landing', note: 'USA, 1969' },
      { rank: 78, name: 'First email sent', note: 'USA, 1971' },
      { rank: 79, name: 'Personal computer revolution begins', note: 'USA, 1975-1977' },
      { rank: 80, name: 'Fall of the Berlin Wall', note: 'Germany, 1989' },
      { rank: 81, name: 'World Wide Web invented', note: 'CERN, 1989' },
      { rank: 82, name: 'Human Genome Project launched', note: 'Global, 1990' },
      { rank: 83, name: 'Soviet Union dissolves', note: 'Eurasia, 1991' },
      { rank: 84, name: 'Dolly the sheep cloned', note: 'UK, 1996' },
      { rank: 85, name: 'Internet goes public/commercial', note: 'Global, 1995' },
      { rank: 86, name: 'Google founded', note: 'USA, 1998' },
      { rank: 87, name: 'Human Genome Project completed', note: 'Global, 2003' },
      { rank: 88, name: 'Smartphone era begins (iPhone)', note: 'USA, 2007' },
      { rank: 89, name: 'Human genome sequencing costs plummet', note: 'Global, 2008' },
      { rank: 90, name: 'Higgs boson discovered', note: 'CERN, 2012' },
      { rank: 91, name: 'CRISPR gene editing breakthrough', note: 'Global, 2012-2015' },
      { rank: 92, name: 'Paris Agreement on climate signed', note: 'Global, 2015' },
      { rank: 93, name: 'First reusable orbital rocket landing', note: 'SpaceX, USA, 2015' },
      { rank: 94, name: 'First image of a black hole captured', note: 'Global, 2019' },
      { rank: 95, name: 'COVID-19 pandemic declared', note: 'Global, 2020' },
      { rank: 96, name: 'mRNA vaccines developed at record speed', note: 'Global, 2020' },
      { rank: 97, name: 'Renewable energy surpasses coal in some grids', note: 'Global, 2020s' },
      { rank: 98, name: 'James Webb Space Telescope begins observations', note: 'Global, 2022' },
      { rank: 99, name: 'Artemis program returns to the Moon (uncrewed test)', note: 'USA, 2022' },
      { rank: 100, name: 'Generative AI reaches mainstream adoption', note: 'Global, 2022-2023' },
    ],
  },
  {
    key: 'mountains',
    icon: Mountain,
    color: '#38bdf8',
    entries: [
      { rank: 1, name: 'Mount Everest', note: 'Nepal/China · 8,849m', detail: "The highest point on Earth above sea level, first summited in 1953." },
      { rank: 2, name: 'K2', note: 'Pakistan/China · 8,611m', detail: "Known as the 'Savage Mountain' for its extreme technical difficulty." },
      { rank: 3, name: 'Kangchenjunga', note: 'Nepal/India · 8,586m', detail: "The third-highest peak on Earth, straddling the Nepal-India border." },
      { rank: 4, name: 'Lhotse', note: 'Nepal/China · 8,516m', detail: "Directly connected to Everest via the South Col." },
      { rank: 5, name: 'Makalu', note: 'Nepal/China · 8,485m', detail: "A distinctive four-sided pyramid peak near Everest." },
      { rank: 6, name: 'Cho Oyu', note: 'Nepal/China · 8,188m', detail: "Considered one of the more approachable 8,000m peaks to climb." },
      { rank: 7, name: 'Dhaulagiri I', note: 'Nepal · 8,167m', detail: "Once believed to be the world's tallest mountain before modern surveys." },
      { rank: 8, name: 'Manaslu', note: 'Nepal · 8,163m', detail: "Its name means 'Mountain of the Spirit' in Sanskrit." },
      { rank: 9, name: 'Nanga Parbat', note: 'Pakistan · 8,126m', detail: "Nicknamed 'Killer Mountain' for its historically high climber fatality rate." },
      { rank: 10, name: 'Annapurna I', note: 'Nepal · 8,091m', detail: "Statistically one of the most dangerous 8,000m peaks to summit." },
      { rank: 11, name: 'Gasherbrum I', note: 'Pakistan/China · 8,080m', detail: "Located in the Karakoram range on the Pakistan-China border." },
      { rank: 12, name: 'Broad Peak', note: 'Pakistan/China · 8,051m', detail: "Named for its wide summit ridge in the Karakoram range." },
      { rank: 13, name: 'Gasherbrum II', note: 'Pakistan/China · 8,035m', detail: "The most frequently climbed of the Gasherbrum group." },
      { rank: 14, name: 'Shishapangma', note: 'China · 8,027m', detail: "The only 8,000m peak located entirely within China." },
      { rank: 15, name: 'Aconcagua', note: 'Argentina · 6,961m', detail: "The highest peak outside Asia, located in the Andes." },
      { rank: 16, name: 'Denali', note: 'USA · 6,190m', detail: "North America's tallest peak, with one of the greatest base-to-summit rises on Earth." },
      { rank: 17, name: 'Kilimanjaro', note: 'Tanzania · 5,895m', detail: "Africa's tallest peak and the world's tallest free-standing mountain." },
      { rank: 18, name: 'Mount Elbrus', note: 'Russia · 5,642m', detail: "Europe's highest peak, located in Russia's Caucasus range." },
      { rank: 19, name: 'Vinson Massif', note: 'Antarctica · 4,892m', detail: "Antarctica's highest peak, part of mountaineering's Seven Summits." },
      { rank: 20, name: 'Puncak Jaya', note: 'Indonesia · 4,884m', detail: "Oceania's highest peak and one of the Seven Summits." },
      { rank: 21, name: 'Pico Cristóbal Colón', note: 'Colombia · 5,730m' },
      { rank: 22, name: 'Mount Ararat', note: 'Türkiye · 5,137m' },
      { rank: 23, name: 'Mount Logan', note: 'Canada · 5,959m' },
      { rank: 24, name: 'Pico de Orizaba', note: 'Mexico · 5,636m' },
      { rank: 25, name: 'Mount Kenya', note: 'Kenya · 5,199m' },
      { rank: 26, name: 'Mauna Kea', note: 'USA (Hawaii) · 4,207m' },
      { rank: 27, name: 'Mount Rainier', note: 'USA · 4,392m' },
      { rank: 28, name: 'Matterhorn', note: 'Switzerland/Italy · 4,478m' },
      { rank: 29, name: 'Mont Blanc', note: 'France/Italy · 4,809m' },
      { rank: 30, name: 'Mount Whitney', note: 'USA · 4,421m' },
    ],
  },
  {
    key: 'rivers',
    icon: Waves,
    color: '#2dd4bf',
    entries: [
      { rank: 1, name: 'Nile', note: 'Africa · ~6,650km', detail: "Historically considered the world's longest river, central to ancient Egyptian civilization." },
      { rank: 2, name: 'Amazon', note: 'South America · ~6,400km', detail: "Carries by far the greatest water volume of any river on Earth." },
      { rank: 3, name: 'Yangtze', note: 'China · ~6,300km', detail: "Asia's longest river and a central artery of Chinese trade and agriculture." },
      { rank: 4, name: 'Mississippi–Missouri', note: 'USA · ~6,275km', detail: "North America's longest river system, historically vital to US commerce." },
      { rank: 5, name: 'Yenisei–Angara', note: 'Russia · ~5,539km', detail: "One of Siberia's major river systems, draining into the Arctic Ocean." },
      { rank: 6, name: 'Yellow River (Huang He)', note: 'China · ~5,464km', detail: "Called the 'Cradle of Chinese Civilization' for its role in early settlement." },
      { rank: 7, name: 'Ob–Irtysh', note: 'Russia/Kazakhstan · ~5,410km', detail: "A major Siberian river system flowing north into the Arctic." },
      { rank: 8, name: 'Congo', note: 'Africa · ~4,700km', detail: "Africa's second-longest river and the world's deepest river." },
      { rank: 9, name: 'Amur–Argun', note: 'Russia/China · ~4,444km', detail: "Forms a long stretch of the Russia-China border." },
      { rank: 10, name: 'Lena', note: 'Russia · ~4,400km', detail: "One of the largest rivers flowing entirely within Russia." },
      { rank: 11, name: 'Mekong', note: 'Southeast Asia · ~4,350km', detail: "A vital waterway for food and transport across six Southeast Asian countries." },
      { rank: 12, name: 'Mackenzie', note: 'Canada · ~4,241km', detail: "Canada's longest river system, draining into the Arctic Ocean." },
      { rank: 13, name: 'Niger', note: 'West Africa · ~4,180km', detail: "West Africa's principal river, vital to regional agriculture." },
      { rank: 14, name: 'Brahmaputra', note: 'Asia · ~3,969km', detail: "One of Asia's major rivers, known for dramatic seasonal flooding." },
      { rank: 15, name: 'Murray–Darling', note: 'Australia · ~3,672km', detail: "Australia's largest river system, critical to its agricultural heartland." },
      { rank: 16, name: 'Volga', note: 'Russia · ~3,531km', detail: "Europe's longest river and a historic artery of Russian trade." },
      { rank: 17, name: 'Madeira', note: 'South America · ~3,250km', detail: "The Amazon's largest tributary by volume." },
      { rank: 18, name: 'Purus', note: 'South America · ~3,211km', detail: "One of the most sinuous rivers in the Amazon basin." },
      { rank: 19, name: 'Yukon', note: 'Canada/USA · ~3,190km', detail: "A historic route during the Klondike Gold Rush." },
      { rank: 20, name: 'Indus', note: 'Asia · ~3,180km', detail: "Gave its name to the Indus Valley Civilization and modern India." },
      { rank: 21, name: 'Paraná', note: 'South America · ~4,880km' },
      { rank: 22, name: 'Rio Grande', note: 'USA/Mexico · ~3,051km' },
      { rank: 23, name: 'São Francisco', note: 'Brazil · ~2,914km' },
      { rank: 24, name: 'Danube', note: 'Europe · ~2,850km' },
      { rank: 25, name: 'Tocantins', note: 'Brazil · ~2,850km' },
      { rank: 26, name: 'Salween', note: 'Asia · ~2,815km' },
      { rank: 27, name: 'Euphrates', note: 'Middle East · ~2,800km' },
      { rank: 28, name: 'Ganges', note: 'South Asia · ~2,525km' },
      { rank: 29, name: 'Zambezi', note: 'Africa · ~2,574km' },
      { rank: 30, name: 'Amu Darya', note: 'Central Asia · ~2,400km' },
      { rank: 31, name: 'Orinoco', note: 'South America · ~2,140km' },
      { rank: 32, name: 'Syr Darya', note: 'Central Asia · ~2,212km' },
      { rank: 33, name: 'Colorado River', note: 'USA/Mexico · ~2,330km' },
      { rank: 34, name: 'Tigris', note: 'Middle East · ~1,900km' },
      { rank: 35, name: 'Columbia River', note: 'USA/Canada · ~2,000km' },
    ],
  },
  {
    key: 'buildings',
    icon: Building2,
    color: '#c084fc',
    entries: [
      { rank: 1, name: 'Burj Khalifa', note: 'Dubai · 828m', detail: "The world's tallest building since 2010, anchoring Dubai's skyline." },
      { rank: 2, name: 'Merdeka 118', note: 'Kuala Lumpur · 679m', detail: "Malaysia's tallest building and the world's second-tallest, completed in 2023." },
      { rank: 3, name: 'Shanghai Tower', note: 'Shanghai · 632m', detail: "China's tallest building, featuring a distinctive twisting form." },
      { rank: 4, name: 'Abraj Al-Bait Clock Tower', note: 'Mecca · 601m', detail: "Overlooks Mecca's Grand Mosque and houses the world's largest clock face." },
      { rank: 5, name: 'Ping An Finance Center', note: 'Shenzhen · 599m', detail: "One of Shenzhen's defining skyscrapers." },
      { rank: 6, name: 'Lotte World Tower', note: 'Seoul · 555m', detail: "South Korea's tallest building, in Seoul." },
      { rank: 7, name: 'One World Trade Center', note: 'New York · 541m', detail: "The tallest building in the Western Hemisphere, built at the original WTC site." },
      { rank: 8, name: 'Guangzhou CTF Finance Centre', note: 'Guangzhou · 530m', detail: "A mixed-use tower combining offices, apartments, and a hotel." },
      { rank: 9, name: 'Tianjin CTF Finance Centre', note: 'Tianjin · 530m', detail: "Part of the CTF Finance Centre family of supertall towers." },
      { rank: 10, name: 'CITIC Tower', note: 'Beijing · 528m', detail: "Beijing's tallest building, nicknamed 'China Zun' for its ancient-vessel shape." },
      { rank: 11, name: 'Taipei 101', note: 'Taipei · 508m', detail: "Held the world's-tallest title from 2004-2010 and features a giant tuned-mass damper." },
      { rank: 12, name: 'Shanghai World Financial Center', note: 'Shanghai · 492m', detail: "Nicknamed the 'bottle opener' for its distinctive trapezoidal aperture." },
      { rank: 13, name: 'International Commerce Centre', note: 'Hong Kong · 484m', detail: "Hong Kong's tallest building, part of the West Kowloon skyline." },
      { rank: 14, name: 'Central Park Tower', note: 'New York · 472m', detail: "The tallest residential building in the world." },
      { rank: 15, name: 'Lakhta Center', note: 'St. Petersburg · 462m', detail: "Russia's tallest building, headquarters of Gazprom in St. Petersburg." },
      { rank: 16, name: 'Vincom Landmark 81', note: 'Ho Chi Minh City · 461m', detail: "Vietnam's tallest building, in Ho Chi Minh City." },
      { rank: 17, name: 'Changsha IFS Tower T1', note: 'Changsha · 452m', detail: "One of two towers forming Changsha's IFS complex." },
      { rank: 18, name: 'Petronas Tower 1', note: 'Kuala Lumpur · 452m', detail: "Part of the twin towers that held the world-tallest title 1998-2004." },
      { rank: 19, name: 'Petronas Tower 2', note: 'Kuala Lumpur · 452m', detail: "Connected to its twin by a famous skybridge." },
      { rank: 20, name: 'Suzhou IFS', note: 'Suzhou · 450m', detail: "One of the tallest buildings in China's Jiangsu province." },
      { rank: 21, name: 'Zifeng Tower', note: 'Nanjing · 450m' },
      { rank: 22, name: 'The Exchange 106', note: 'Kuala Lumpur · 445m' },
      { rank: 23, name: 'KK100', note: 'Shenzhen · 442m' },
      { rank: 24, name: 'Willis Tower', note: 'Chicago · 442m' },
      { rank: 25, name: 'Guangzhou International Finance Center', note: 'Guangzhou · 439m' },
      { rank: 26, name: 'Wuhan Center Tower', note: 'Wuhan · 438m' },
      { rank: 27, name: 'One Vanderbilt', note: 'New York · 427m' },
      { rank: 28, name: 'Marina 101', note: 'Dubai · 425m' },
      { rank: 29, name: 'Trump International Hotel & Tower', note: 'Chicago · 423m' },
      { rank: 30, name: '432 Park Avenue', note: 'New York · 426m' },
      { rank: 31, name: 'Princess Tower', note: 'Dubai · 414m' },
      { rank: 32, name: 'Busan Lotte Town Tower', note: 'Busan · 411m' },
      { rank: 33, name: 'Al Hamra Tower', note: 'Kuwait City · 413m' },
      { rank: 34, name: '23 Marina', note: 'Dubai · 393m' },
      { rank: 35, name: '30 Hudson Yards', note: 'New York · 387m' },
      { rank: 36, name: 'Empire State Building', note: 'New York · 381m' },
      { rank: 37, name: 'Elite Residence', note: 'Dubai · 380m' },
      { rank: 38, name: 'Federation Tower (Vostok)', note: 'Moscow · 374m' },
      { rank: 39, name: 'Bank of America Tower', note: 'New York · 366m' },
      { rank: 40, name: 'One Bangkok Tower', note: 'Bangkok · 436m' },
      { rank: 41, name: 'Comcast Technology Center', note: 'Philadelphia · 342m' },
      { rank: 42, name: 'Wilshire Grand Center', note: 'Los Angeles · 335m' },
      { rank: 43, name: 'MahaNakhon', note: 'Bangkok · 314m' },
      { rank: 44, name: 'Keangnam Hanoi Landmark Tower', note: 'Hanoi · 336m' },
      { rank: 45, name: 'Eureka Tower', note: 'Melbourne · 297m' },
      { rank: 46, name: 'Australia 108', note: 'Melbourne · 316m' },
      { rank: 47, name: 'Q1 Tower', note: 'Gold Coast, Australia · 323m' },
      { rank: 48, name: 'Salesforce Tower', note: 'San Francisco · 326m' },
      { rank: 49, name: 'Torre Costanera', note: 'Santiago · 300m' },
      { rank: 50, name: 'Gran Torre Santiago', note: 'Santiago · 300m' },
      { rank: 51, name: 'Torre Reforma', note: 'Mexico City · 246m' },
      { rank: 52, name: 'Baiyoke Tower II', note: 'Bangkok · 304m' },
      { rank: 53, name: '63 Building', note: 'Seoul · 249m' },
      { rank: 54, name: 'Haeundae LCT The Sharp Landmark Tower', note: 'Busan · 412m' },
      { rank: 55, name: 'World One', note: 'Mumbai · 280m' },
    ],
  },
  {
    key: 'population',
    icon: Users2,
    color: '#34d399',
    entries: [
      { rank: 1, name: 'India', note: '~1.44B', detail: "Surpassed China in 2023 to become the world's most populous country." },
      { rank: 2, name: 'China', note: '~1.41B', detail: "The world's second-most populous country after decades at number one." },
      { rank: 3, name: 'United States', note: '~340M', detail: "The most populous country in the Americas." },
      { rank: 4, name: 'Indonesia', note: '~280M', detail: "Southeast Asia's most populous nation, spread across thousands of islands." },
      { rank: 5, name: 'Pakistan', note: '~250M', detail: "One of the fastest-growing large populations in South Asia." },
      { rank: 6, name: 'Nigeria', note: '~230M', detail: "Africa's most populous country, with a rapidly growing youth population." },
      { rank: 7, name: 'Brazil', note: '~217M', detail: "South America's most populous nation." },
      { rank: 8, name: 'Bangladesh', note: '~173M', detail: "One of the most densely populated large countries on Earth." },
      { rank: 9, name: 'Russia', note: '~144M', detail: "The largest country by land area, with a population concentrated west of the Urals." },
      { rank: 10, name: 'Mexico', note: '~130M', detail: "North America's second-most populous country after the US." },
      { rank: 11, name: 'Ethiopia', note: '~127M', detail: "One of Africa's oldest continuously independent nations by population rank." },
      { rank: 12, name: 'Japan', note: '~123M', detail: "A highly urbanized population facing significant demographic aging." },
      { rank: 13, name: 'Philippines', note: '~118M', detail: "A youthful, rapidly growing archipelago nation." },
      { rank: 14, name: 'Egypt', note: '~116M', detail: "The most populous country in the Arab world." },
      { rank: 15, name: 'DR Congo', note: '~102M', detail: "Central Africa's most populous nation, rich in natural resources." },
      { rank: 16, name: 'Vietnam', note: '~100M', detail: "One of Southeast Asia's fastest-growing economies and populations." },
      { rank: 17, name: 'Iran', note: '~89M', detail: "The most populous country in the Middle East by this ranking." },
      { rank: 18, name: 'Türkiye', note: '~87M', detail: "A transcontinental nation bridging Europe and Asia." },
      { rank: 19, name: 'Germany', note: '~84M', detail: "The European Union's most populous member state." },
      { rank: 20, name: 'Thailand', note: '~72M', detail: "Southeast Asia's second-most populous mainland nation." },
      { rank: 21, name: 'United Kingdom', note: '~68M' },
      { rank: 22, name: 'Tanzania', note: '~67M' },
      { rank: 23, name: 'France', note: '~66M' },
      { rank: 24, name: 'South Africa', note: '~60M' },
      { rank: 25, name: 'Italy', note: '~59M' },
      { rank: 26, name: 'Kenya', note: '~56M' },
      { rank: 27, name: 'Myanmar', note: '~55M' },
      { rank: 28, name: 'Colombia', note: '~52M' },
      { rank: 29, name: 'South Korea', note: '~52M' },
      { rank: 30, name: 'Uganda', note: '~48M' },
      { rank: 31, name: 'Sudan', note: '~48M' },
      { rank: 32, name: 'Spain', note: '~48M' },
      { rank: 33, name: 'Algeria', note: '~46M' },
      { rank: 34, name: 'Argentina', note: '~46M' },
      { rank: 35, name: 'Iraq', note: '~45M' },
      { rank: 36, name: 'Afghanistan', note: '~42M' },
      { rank: 37, name: 'Canada', note: '~39M' },
      { rank: 38, name: 'Poland', note: '~38M' },
      { rank: 39, name: 'Morocco', note: '~38M' },
      { rank: 40, name: 'Yemen', note: '~34M' },
      { rank: 41, name: 'Angola', note: '~36M' },
      { rank: 42, name: 'Ukraine', note: '~36M' },
      { rank: 43, name: 'Uzbekistan', note: '~35M' },
      { rank: 44, name: 'Malaysia', note: '~34M' },
      { rank: 45, name: 'Ghana', note: '~34M' },
      { rank: 46, name: 'Peru', note: '~34M' },
      { rank: 47, name: 'Saudi Arabia', note: '~36M' },
      { rank: 48, name: 'Mozambique', note: '~33M' },
      { rank: 49, name: 'Madagascar', note: '~30M' },
      { rank: 50, name: 'Nepal', note: '~30M' },
      { rank: 51, name: 'Venezuela', note: '~28M' },
      { rank: 52, name: 'Ivory Coast', note: '~29M' },
      { rank: 53, name: 'Cameroon', note: '~28M' },
      { rank: 54, name: 'Australia', note: '~26M' },
      { rank: 55, name: 'Niger', note: '~27M' },
      { rank: 56, name: 'North Korea', note: '~26M' },
      { rank: 57, name: 'Sri Lanka', note: '~22M' },
      { rank: 58, name: 'Mali', note: '~23M' },
      { rank: 59, name: 'Burkina Faso', note: '~23M' },
      { rank: 60, name: 'Syria', note: '~23M' },
      { rank: 61, name: 'Malawi', note: '~21M' },
      { rank: 62, name: 'Chile', note: '~20M' },
      { rank: 63, name: 'Kazakhstan', note: '~20M' },
      { rank: 64, name: 'Zambia', note: '~20M' },
      { rank: 65, name: 'Ecuador', note: '~18M' },
      { rank: 66, name: 'Netherlands', note: '~18M' },
      { rank: 67, name: 'Somalia', note: '~18M' },
      { rank: 68, name: 'Senegal', note: '~18M' },
      { rank: 69, name: 'Chad', note: '~18M' },
      { rank: 70, name: 'Cambodia', note: '~17M' },
      { rank: 71, name: 'Guatemala', note: '~18M' },
      { rank: 72, name: 'Zimbabwe', note: '~16M' },
      { rank: 73, name: 'Guinea', note: '~14M' },
      { rank: 74, name: 'Rwanda', note: '~14M' },
      { rank: 75, name: 'Benin', note: '~13M' },
      { rank: 76, name: 'Burundi', note: '~13M' },
      { rank: 77, name: 'South Sudan', note: '~11M' },
      { rank: 78, name: 'Tunisia', note: '~12M' },
      { rank: 79, name: 'Bolivia', note: '~12M' },
      { rank: 80, name: 'Belgium', note: '~12M' },
      { rank: 81, name: 'Cuba', note: '~11M' },
      { rank: 82, name: 'Haiti', note: '~11M' },
      { rank: 83, name: 'Dominican Republic', note: '~11M' },
      { rank: 84, name: 'Jordan', note: '~11M' },
      { rank: 85, name: 'United Arab Emirates', note: '~10M' },
      { rank: 86, name: 'Sweden', note: '~10M' },
      { rank: 87, name: 'Czechia', note: '~11M' },
      { rank: 88, name: 'Greece', note: '~10M' },
      { rank: 89, name: 'Portugal', note: '~10M' },
      { rank: 90, name: 'Papua New Guinea', note: '~10M' },
      { rank: 91, name: 'Azerbaijan', note: '~10M' },
      { rank: 92, name: 'Honduras', note: '~10M' },
      { rank: 93, name: 'Hungary', note: '~10M' },
      { rank: 94, name: 'Tajikistan', note: '~10M' },
      { rank: 95, name: 'Belarus', note: '~9M' },
      { rank: 96, name: 'Austria', note: '~9M' },
      { rank: 97, name: 'Israel', note: '~9M' },
      { rank: 98, name: 'Switzerland', note: '~9M' },
      { rank: 99, name: 'Togo', note: '~9M' },
      { rank: 100, name: 'Sierra Leone', note: '~8M' },
    ],
  },
  {
    key: 'filmBoxOffice',
    icon: Clapperboard,
    color: '#fb7185',
    entries: [
      { rank: 1, name: 'Avatar', note: '2009 · ~$2.92B', detail: "James Cameron's 2009 sci-fi epic, the highest-grossing film ever unadjusted for inflation." },
      { rank: 2, name: 'Avengers: Endgame', note: '2019 · ~$2.80B', detail: "Marvel's culmination of over a decade of interconnected films." },
      { rank: 3, name: 'Avatar: The Way of Water', note: '2022 · ~$2.32B', detail: "The 2022 sequel that returned Cameron's saga to the top ranks." },
      { rank: 4, name: 'Titanic', note: '1997 · ~$2.26B', detail: "James Cameron's 1997 epic held the top spot for over a decade." },
      { rank: 5, name: 'Star Wars: The Force Awakens', note: '2015 · ~$2.07B', detail: "Revived the Star Wars saga for a new generation in 2015." },
      { rank: 6, name: 'Avengers: Infinity War', note: '2018 · ~$2.05B', detail: "Set up the culmination of the Marvel Infinity Saga." },
      { rank: 7, name: 'Spider-Man: No Way Home', note: '2021 · ~$1.92B', detail: "Brought together three eras of Spider-Man actors on screen." },
      { rank: 8, name: 'Inside Out 2', note: '2024 · ~$1.70B', detail: "Pixar's 2024 sequel became one of the highest-grossing animated films ever." },
      { rank: 9, name: 'Jurassic World', note: '2015 · ~$1.67B', detail: "Revived the Jurassic Park franchise for a new generation in 2015." },
      { rank: 10, name: 'The Lion King', note: '2019 · ~$1.66B', detail: "Disney's 2019 photorealistic remake of its 1994 animated classic." },
      { rank: 11, name: 'The Avengers', note: '2012 · ~$1.52B', detail: "The 2012 film that proved shared cinematic universes could work at scale." },
      { rank: 12, name: 'Furious 7', note: '2015 · ~$1.52B', detail: "A tribute film following star Paul Walker's death during production." },
      { rank: 13, name: 'Top Gun: Maverick', note: '2022 · ~$1.49B', detail: "A 2022 legacy sequel decades after the original, a post-pandemic box-office landmark." },
      { rank: 14, name: 'Frozen II', note: '2019 · ~$1.45B', detail: "Disney's sequel to one of the best-selling animated films of all time." },
      { rank: 15, name: 'Barbie', note: '2023 · ~$1.45B', detail: "Greta Gerwig's 2023 film became a cultural and box-office phenomenon." },
      { rank: 16, name: 'Avengers: Age of Ultron', note: '2015 · ~$1.40B', detail: "The second Avengers ensemble film in the Marvel Cinematic Universe." },
      { rank: 17, name: 'The Super Mario Bros. Movie', note: '2023 · ~$1.36B', detail: "Adapted Nintendo's flagship franchise into an animated blockbuster." },
      { rank: 18, name: 'Black Panther', note: '2018 · ~$1.35B', detail: "A cultural landmark as Marvel's first film led by a Black superhero." },
      { rank: 19, name: 'Harry Potter and the Deathly Hallows – Part 2', note: '2011 · ~$1.34B', detail: "The finale to the Harry Potter film saga." },
      { rank: 20, name: 'Star Wars: The Last Jedi', note: '2017 · ~$1.33B', detail: "The contentious middle chapter of the sequel trilogy." },
      { rank: 21, name: 'Jurassic World: Fallen Kingdom', note: '2018 · ~$1.31B' },
      { rank: 22, name: 'Frozen', note: '2013 · ~$1.28B' },
      { rank: 23, name: 'Beauty and the Beast', note: '2017 · ~$1.27B' },
      { rank: 24, name: 'Incredibles 2', note: '2018 · ~$1.24B' },
      { rank: 25, name: 'The Fate of the Furious', note: '2017 · ~$1.24B' },
      { rank: 26, name: 'Iron Man 3', note: '2013 · ~$1.21B' },
      { rank: 27, name: 'Minions', note: '2015 · ~$1.16B' },
      { rank: 28, name: 'Captain America: Civil War', note: '2016 · ~$1.15B' },
      { rank: 29, name: 'Aquaman', note: '2018 · ~$1.15B' },
      { rank: 30, name: 'The Lord of the Rings: The Return of the King', note: '2003 · ~$1.15B' },
      { rank: 31, name: 'Spider-Man: Far From Home', note: '2019 · ~$1.13B' },
      { rank: 32, name: 'Captain Marvel', note: '2019 · ~$1.13B' },
      { rank: 33, name: 'Transformers: Dark of the Moon', note: '2011 · ~$1.12B' },
      { rank: 34, name: 'Skyfall', note: '2012 · ~$1.11B' },
      { rank: 35, name: 'Transformers: Age of Extinction', note: '2014 · ~$1.10B' },
      { rank: 36, name: 'The Dark Knight Rises', note: '2012 · ~$1.08B' },
      { rank: 37, name: 'Toy Story 4', note: '2019 · ~$1.07B' },
      { rank: 38, name: 'Pirates of the Caribbean: Dead Man’s Chest', note: '2006 · ~$1.07B' },
      { rank: 39, name: 'Joker', note: '2019 · ~$1.07B' },
      { rank: 40, name: 'Star Wars: Episode I – The Phantom Menace', note: '1999 · ~$1.03B' },
      { rank: 41, name: 'Toy Story 3', note: '2010 · ~$1.07B' },
      { rank: 42, name: 'Pirates of the Caribbean: On Stranger Tides', note: '2011 · ~$1.05B' },
      { rank: 43, name: 'Rogue One: A Star Wars Story', note: '2016 · ~$1.06B' },
      { rank: 44, name: 'Aladdin', note: '2019 · ~$1.05B' },
      { rank: 45, name: 'Despicable Me 3', note: '2017 · ~$1.03B' },
      { rank: 46, name: 'Finding Dory', note: '2016 · ~$1.03B' },
      { rank: 47, name: 'Alice in Wonderland', note: '2010 · ~$1.03B' },
      { rank: 48, name: 'Zootopia', note: '2016 · ~$1.02B' },
      { rank: 49, name: 'The Dark Knight', note: '2008 · ~$1.01B' },
      { rank: 50, name: 'Jurassic Park', note: '1993 · ~$1.03B' },
    ],
  },
  {
    key: 'youtubeViews',
    icon: PlaySquare,
    color: '#ef4444',
    entries: [
      { rank: 1, name: 'Baby Shark Dance', note: 'Pinkfong · ~15.4B views', detail: "A children's sing-along that became the first video ever to reach 10 billion views." },
      { rank: 2, name: 'Despacito', note: 'Luis Fonsi ft. Daddy Yankee · ~8.7B views', detail: "The Spanish-language hit that broke YouTube and Spotify streaming records worldwide in 2017." },
      { rank: 3, name: 'Bath Song', note: 'Cocomelon · ~7.2B views', detail: "One of several Cocomelon nursery-rhyme videos to rank among YouTube's most-viewed ever." },
      { rank: 4, name: 'Wheels on the Bus', note: 'Cocomelon · ~6.9B views', detail: "A classic nursery rhyme reimagined by the children's channel Cocomelon." },
      { rank: 5, name: 'Johny Johny Yes Papa', note: 'LooLoo Kids · ~6.8B views', detail: "A nursery-rhyme video from Romania-based LooLoo Kids that became a global children's hit." },
      { rank: 6, name: 'See You Again', note: 'Wiz Khalifa ft. Charlie Puth · ~6.4B views', detail: "Written as a tribute to actor Paul Walker for the Furious 7 soundtrack." },
      { rank: 7, name: 'Shape of You', note: 'Ed Sheeran · ~6.3B views', detail: "One of the best-selling singles of the streaming era." },
      { rank: 8, name: 'Uptown Funk', note: 'Mark Ronson ft. Bruno Mars · ~5.3B views', detail: "A retro-funk revival that topped charts worldwide in 2015." },
      { rank: 9, name: 'Learning Colors – Nursery Rhymes', note: 'ChuChuTV · ~5.2B views', detail: "An educational nursery-rhyme video from the India-based ChuChu TV channel." },
      { rank: 10, name: 'Masha and the Bear – Recipe for Disaster', note: 'Get Movies · ~5.1B views', detail: "An episode of the Russian animated series that became a global streaming phenomenon." },
      { rank: 11, name: 'Gangnam Style', note: 'PSY · ~5.0B views', detail: "The first video ever to reach 1 billion views, sparking a global viral-dance craze in 2012." },
      { rank: 12, name: 'Sugar', note: 'Maroon 5 · ~4.6B views', detail: "Famous for its music video filmed by crashing real strangers' weddings." },
      { rank: 13, name: 'Believer', note: 'Imagine Dragons · ~4.5B views', detail: "One of the band's biggest global rock-radio and streaming hits." },
      { rank: 14, name: 'Roar', note: 'Katy Perry · ~3.7B views', detail: "An empowerment anthem from Perry's Prism album." },
      { rank: 15, name: 'Faded', note: 'Alan Walker · ~3.8B views', detail: "A Norwegian DJ's electronic hit that became one of YouTube's most-viewed music videos." },
      { rank: 16, name: 'Counting Stars', note: 'OneRepublic · ~3.6B views', detail: "One of the defining pop-rock radio hits of the early 2010s." },
      { rank: 17, name: 'Sorry', note: 'Justin Bieber · ~3.6B views', detail: "Featured a widely imitated dance routine performed by New Zealand dance group ReQuest." },
      { rank: 18, name: 'Thinking Out Loud', note: 'Ed Sheeran · ~3.5B views', detail: "A wedding-favorite ballad from Sheeran's multiplatinum album x." },
      { rank: 19, name: 'Waka Waka (This Time for Africa)', note: 'Shakira · ~3.4B views', detail: "The official song of the 2010 FIFA World Cup in South Africa." },
      { rank: 20, name: 'Dance Monkey', note: 'Tones and I · ~2.3B views', detail: "An Australian breakout hit that topped charts in over 30 countries." },
    ],
  },
  {
    key: 'esportsEarnings',
    icon: Gamepad2,
    color: '#818cf8',
    entries: [
      { rank: 1, name: 'Dota 2', note: '~$350M+ total prize money', detail: "Valve's flagship title, driven largely by The International's crowdfunded prize pool, the largest in esports history." },
      { rank: 2, name: 'Fortnite', note: '~$170M+ total prize money', detail: "Epic Games' battle royale paid out a record-setting $30M+ at its 2019 World Cup alone." },
      { rank: 3, name: 'Counter-Strike (CS:GO/CS2)', note: '~$180M+ total prize money', detail: "One of the longest-running competitive shooters, anchored by Majors and top-tier leagues." },
      { rank: 4, name: 'League of Legends', note: '~$140M+ total prize money', detail: "Riot Games' MOBA anchors the annual World Championship, one of esports' most-watched events." },
      { rank: 5, name: 'PUBG Mobile', note: '~$70M+ total prize money', detail: "A mobile battle royale with a massive competitive scene across Asia." },
      { rank: 6, name: 'Rainbow Six Siege', note: '~$45M+ total prize money', detail: "A tactical shooter known for its Six Invitational world championship." },
      { rank: 7, name: 'Overwatch / Overwatch 2', note: '~$45M+ total prize money', detail: "Blizzard's hero shooter built a franchised league modeled on traditional sports." },
      { rank: 8, name: 'Valorant', note: '~$45M+ total prize money', detail: "Riot's tactical shooter rapidly built a major international circuit after its 2020 launch." },
      { rank: 9, name: 'Arena of Valor', note: '~$40M+ total prize money', detail: "A mobile MOBA especially dominant in Southeast Asian esports." },
      { rank: 10, name: 'StarCraft II', note: '~$35M+ total prize money', detail: "The successor to one of esports' founding titles, still central to South Korea's competitive scene." },
      { rank: 11, name: 'Free Fire', note: '~$35M+ total prize money', detail: "One of the most-played mobile battle royales, especially across Latin America and South Asia." },
      { rank: 12, name: 'Mobile Legends: Bang Bang', note: '~$30M+ total prize money', detail: "A mobile MOBA that anchors major esports scenes across Southeast Asia." },
      { rank: 13, name: 'Apex Legends', note: '~$25M+ total prize money', detail: "Respawn's battle royale hosts the Apex Legends Global Series." },
      { rank: 14, name: 'Hearthstone', note: '~$25M+ total prize money', detail: "Blizzard's digital card game built one of esports' earliest major individual-competitor circuits." },
      { rank: 15, name: 'Call of Duty League', note: '~$25M+ total prize money', detail: "A franchised city-based league modeled directly on traditional sports leagues." },
      { rank: 16, name: 'Rocket League', note: '~$20M+ total prize money', detail: "A physics-based 'soccer with cars' game with a dedicated global league." },
      { rank: 17, name: 'StarCraft: Brood War', note: '~$15M+ total prize money (legacy era)', detail: "The legendary title that essentially founded South Korea's professional esports industry in the late 1990s." },
      { rank: 18, name: 'Street Fighter', note: '~$15M+ total prize money', detail: "One of the fighting-game genre's flagship titles, central to the long-running Evo championship." },
      { rank: 19, name: 'Super Smash Bros. (Melee/Ultimate)', note: '~$10M+ total prize money', detail: "A community-driven competitive scene that has thrived for over two decades." },
      { rank: 20, name: 'Warcraft III', note: '~$8M+ total prize money (legacy era)', detail: "An early real-time-strategy esport that helped define competitive gaming's first generation." },
    ],
  },
  {
    key: 'albumSales',
    icon: Disc3,
    color: '#fb923c',
    entries: [
      { rank: 1, name: 'Thriller', note: 'Michael Jackson · ~70M (est.)', detail: "The best-selling album of all time, spawning seven top-10 singles from a single record." },
      { rank: 2, name: 'Back in Black', note: 'AC/DC · ~50M (est.)', detail: "Recorded as a tribute after singer Bon Scott's death, it remains rock's best-selling album." },
      { rank: 3, name: 'The Dark Side of the Moon', note: 'Pink Floyd · ~45M (est.)', detail: "Spent a record 900+ weeks on the US Billboard album chart." },
      { rank: 4, name: 'The Bodyguard: Original Soundtrack', note: 'Whitney Houston · ~45M (est.)', detail: "Anchored by 'I Will Always Love You,' one of the best-selling singles ever." },
      { rank: 5, name: 'Bat Out of Hell', note: 'Meat Loaf · ~43M (est.)', detail: "A theatrical rock-opera album that has sold steadily for over four decades." },
      { rank: 6, name: 'Their Greatest Hits (1971–1975)', note: 'Eagles · ~42M (est.)', detail: "One of the best-selling compilation albums in US chart history." },
      { rank: 7, name: 'Saturday Night Fever', note: 'Various Artists / Bee Gees · ~40M (est.)', detail: "The disco-era soundtrack that defined a musical decade." },
      { rank: 8, name: 'Rumours', note: 'Fleetwood Mac · ~40M (est.)', detail: "Written amid the band's internal breakups, it became one of rock's defining records." },
      { rank: 9, name: 'Come On Over', note: 'Shania Twain · ~40M (est.)', detail: "The best-selling studio album by a woman in country-pop history." },
      { rank: 10, name: 'Grease: The Original Soundtrack', note: 'Various Artists · ~38M (est.)', detail: "The soundtrack to the hit 1978 musical film starring John Travolta and Olivia Newton-John." },
      { rank: 11, name: "21", note: 'Adele · ~31M (est.)', detail: "Anchored by 'Rolling in the Deep,' one of the defining albums of the 2010s." },
      { rank: 12, name: 'Music Box', note: 'Mariah Carey · ~30M (est.)', detail: "Featured the hit ballad 'Hero,' among Carey's signature songs." },
      { rank: 13, name: 'Metallica (The Black Album)', note: 'Metallica · ~30M (est.)', detail: "Brought thrash metal into the commercial mainstream." },
      { rank: 14, name: 'Jagged Little Pill', note: 'Alanis Morissette · ~33M (est.)', detail: "A raw, confessional rock record that defined 1990s alternative music." },
      { rank: 15, name: 'Falling into You', note: 'Celine Dion · ~32M (est.)', detail: "Won the Grammy for Album of the Year in 1997." },
      { rank: 16, name: 'The Immaculate Collection', note: 'Madonna · ~30M (est.)', detail: "A greatest-hits compilation spanning Madonna's 1980s pop dominance." },
      { rank: 17, name: 'Purple Rain', note: 'Prince and the Revolution · ~25M (est.)', detail: "The soundtrack to Prince's semi-autobiographical film of the same name." },
      { rank: 18, name: 'Cracked Rear View', note: 'Hootie & the Blowfish · ~21M (est.)', detail: "One of the best-selling debut albums in US music history." },
      { rank: 19, name: "Please Hammer, Don't Hurt 'Em", note: 'MC Hammer · ~18M (est.)', detail: "Anchored by 'U Can't Touch This,' one of the best-selling hip-hop albums of its era." },
      { rank: 20, name: 'Boston', note: 'Boston · ~17M (est.)', detail: "One of the best-selling debut albums by an American rock band." },
    ],
  },
  {
    key: 'humanRecords',
    icon: Medal,
    color: '#a3e635',
    entries: [
      { rank: 1, name: 'Robert Wadlow', note: 'Tallest man ever verified · 272cm', detail: "The American 'Alton Giant' remains the tallest person in recorded history, verified by Guinness." },
      { rank: 2, name: 'Jeanne Calment', note: 'Longest verified human lifespan · 122 years, 164 days', detail: "The French supercentenarian's 1997 death still stands as the longest confirmed human life." },
      { rank: 3, name: 'Usain Bolt', note: 'Fastest 100m sprint · 9.58 seconds', detail: "Set at the 2009 World Championships in Berlin, still the fastest 100m ever officially timed." },
      { rank: 4, name: 'Michael Phelps', note: 'Most Olympic gold medals · 23', detail: "The American swimmer's total gold-medal count remains unmatched across all Olympic history." },
      { rank: 5, name: 'Chandra Bahadur Dangi', note: 'Shortest verified adult human (mobile) · 54.6cm', detail: "The Nepali man held the record for shortest mobile adult until his death in 2015." },
      { rank: 6, name: 'Jon Brower Minnoch', note: 'Heaviest human ever recorded · ~635kg at peak', detail: "The American man holds the record for heaviest verified human body mass in medical history." },
      { rank: 7, name: 'Xie Qiuping', note: 'Longest hair ever verified · 5.6 meters', detail: "The Chinese woman grew her hair for decades before it was officially measured by Guinness." },
      { rank: 8, name: 'Lee Redmond', note: 'Longest fingernails ever (female) · combined 8.65m', detail: "The American grew her nails for nearly 30 years before losing them in a 2009 car accident." },
      { rank: 9, name: 'Eliud Kipchoge', note: 'Fastest record-eligible marathon · 2:01:09', detail: "The Kenyan runner's Berlin Marathon time stands as the fastest record-eligible marathon ever run." },
      { rank: 10, name: 'Brigid Kosgei', note: "Fastest women's marathon · 2:14:04", detail: "The Kenyan runner's 2019 Chicago Marathon time remains the fastest women's marathon on record." },
      { rank: 11, name: 'Mrs. Vassilyev', note: 'Most children born to one mother · 69 (historical claim)', detail: "A historically cited Guinness record of 69 children from multiple births to one 18th-century Russian woman." },
      { rank: 12, name: 'Wim Hof', note: "Cold-endurance records · the 'Iceman'", detail: "The Dutch 'Iceman' set multiple Guinness records for cold-exposure endurance." },
      { rank: 13, name: 'Nirmal Purja', note: 'Fastest ascent of all 14 peaks above 8,000m · ~6 months, 6 days', detail: "The Nepali mountaineer shattered the previous record of nearly eight years." },
      { rank: 14, name: 'Kilian Jornet', note: 'Speed records on Everest and other major peaks', detail: "The Spanish ultrarunner holds speed records on some of the world's most iconic mountains." },
      { rank: 15, name: 'Ashrita Furman', note: 'Most Guinness World Records held · 200+', detail: "The American record-breaker holds the record for holding the most records simultaneously." },
      { rank: 16, name: 'Garry Kasparov', note: 'Youngest undisputed World Chess Champion · age 22', detail: "The Soviet-Russian grandmaster held the title from 1985, a benchmark later approached under different formats." },
      { rank: 17, name: 'Novak Djokovic', note: "Most Grand Slam men's singles titles · 24", detail: "The Serbian tennis player surpassed the long-standing record held by Roger Federer and Rafael Nadal." },
      { rank: 18, name: 'Cristiano Ronaldo', note: 'Most goals in men\'s international football history · 130+', detail: "The Portuguese forward holds the record for most goals scored for a national team." },
      { rank: 19, name: 'Simone Biles', note: 'Most world championship medals in gymnastics history', detail: "The American gymnast's combined Olympic and World Championship medal haul is the most in the sport's history." },
      { rank: 20, name: 'Ed Stafford', note: 'First person to walk the entire length of the Amazon River', detail: "The British explorer completed the nearly 4,000-mile trek over two and a half years." },
    ],
  },
];
