import { Sparkles, Smartphone, FileJson, ShieldCheck, type LucideIcon } from 'lucide-react';

// UNITAS asset one-click downloads: the brand mark, the PWA icon, the web app
// manifest and the cryptographic ownership manifest (regenerated by
// scripts/ownership-fingerprint.mjs on every build). All four already ship
// under /public, so each tile is a plain same-origin `<a download>` -- no
// packaging step, no server route, no bandwidth beyond the static file that
// is served anyway. Labels resolve from the `Assets.items.*` namespace.

export interface UnitasAsset {
  key: string;
  /** public path (same origin). */
  href: string;
  /** suggested filename for the `download` attribute. */
  fileName: string;
  icon: LucideIcon;
  color: string;
  glow: string;
}

export const UNITAS_ASSETS: UnitasAsset[] = [
  { key: 'mark', href: '/assets/svg/unitas-mark.svg', fileName: 'unitas-mark.svg', icon: Sparkles, color: '#22d3ee', glow: '#67e8f9' },
  { key: 'icon', href: '/icons/icon-512.png', fileName: 'unitas-icon-512.png', icon: Smartphone, color: '#a78bfa', glow: '#c4b5fd' },
  { key: 'manifest', href: '/manifest.json', fileName: 'unitas-manifest.json', icon: FileJson, color: '#facc15', glow: '#fde047' },
  { key: 'ownership', href: '/ownership-manifest.json', fileName: 'unitas-ownership-manifest.json', icon: ShieldCheck, color: '#34d399', glow: '#6ee7b7' },
];
